apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapdrop
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/snapdrop
    repoURL: https://github.com/alex-phillips/helm-charts
    targetRevision: HEAD
    helm:
      values: |
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: drop.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
