tdarr:
  controller:
    labels:
      pvc: "true"
      nfs: "true"
  image:
    tag: latest
  env:
    TZ: America/New_York
  persistence:
    config:
      enabled: true
      retain: true
      size: 10Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    data:
      enabled: true
      retain: true
      size: 256Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    media:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/other/movies
  ingress:
    main:
      enabled: true
      hosts:
      - host: tdr.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
