node-red:
  controller:
    labels:
      pvc: "true"
  image:
    tag: latest
  env:
    TZ: America/New_York
  persistence:
    data:
      enabled: true
      retain: true
      size: 50Mi
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: node.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  # required for initial volume / data creation per: https://github.com/k8s-at-home/charts/issues/537
  # podSecurityContext:
  #   runAsUser: 1000
  #   runAsGroup: 1000
  #   fsGroup: 1000
  additionalContainers:
    duplicacy:
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "30 03 * * *"
        - name: BACKUP_NAME
          value: gcd-node-red
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/node-red
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: dc718e37-926f-4f73-846d-0b918b051fe4
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: data
