node-red:
  image:
    repository: ghcr.io/k8s-at-home/node-red
    tag: v2.1.3

  env:
    TZ: America/New_York

  persistence:
    data:
      enabled: true
      retain: true
      size: 50Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    rclone-config:
      enabled: true
      mountPath: "-"
      type: custom
      volumeSpec:
        secret:
          secretName: rclone
          items:
            - key: config
              path: rclone.conf

  ingress:
    main:
      enabled: true
      hosts:
      - host: node.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/node-red
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /root/.config/rclone
          name: rclone-config

  additionalContainers:
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "30 03 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: dc718e37-926f-4f73-846d-0b918b051fe4
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/node-red
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /root/.config/rclone
          name: rclone-config
