apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    path: charts/tautulli
    repoURL: https://github.com/alex-phillips/helm-charts
    targetRevision: HEAD
    helm:
      values: |
        persistence:
          config:
            enabled: true
            existingClaim: tautulli
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: ttl.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
        additionalContainers:
          - name: duplicacy
            image: alexphillips/duplicacy
            env:
              - name: TZ
                value: America/New_York
              - name: SCHEDULE
                value: "45 0 * * *"
              - name: BACKUP_NAME
                value: gcd-tautulli
              - name: BACKUP_LOCATION
                value: gcd://duplicacy_backup/tautulli
              - name: HC_API_URL
                value: https://hc.w00t.cloud/ping
              - name: CHECK_UUID
                value: 91105625-60df-42da-a496-a6ed877e39dc
              - name: DUPLICACY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: password
              - name: GCD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: gcd_token
            volumeMounts:
              - mountPath: /data
                name: config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
