apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone
  namespace: apps
spec:
  encryptedData:
    rpc_secret: AgDOgfbjCgmdkL8Q+BM7hHjaruxaMhIZFzigMr8RKEpQE8GLCQw2TZGJXhXP6io0rSF/i5Yr0AEh1SaR6JY8SEW0L37f1pSMet2aYEIiu8OCZmgsujE5ZBb9idRL6poiXAFNNKNcydsEuq7QYFbG/XCTeqxPOT/XwuvjzeBezIlkDlnnlIF0LgltX7rhDdBIVsh0CDfH9rdDFEFWiFB12Mdh08aC3IC1Ub4yIw/1igS5i/a7Mz9kQ29HBt5YWNOUOnMen39hvhqgG0mG+6cyjY5p2OZ1RZrAxdAo4KSh8po8umNa2Hj3DdM2Oj2UjlKscrSC+OOeB9dNoM5Dp0ncGFIhYPs+XyDO+670Cc3M4AIIhhCFXwf4klaSJ673BxahufFKKZbPiYY7UFkRV1l6z73xtkXAyi1i5WpRMoPpAJuTYcvqDjrqTe9vmHlHuj5+ZrbFtZgt9iM6P/Bc06U3/2QrENufLaaRqGcJx+TF9nfEMgf0wiKV0ELnL7GWXmxGt33X0Kd/mOqFBgW6bRsdRmJ1WiUfwJ5jquBUZFDitpigWb6/dCRecfpO0AmrFeTwKxH+p3wZ9u4iD9IfEp3drXQFSZCtKRWSfzB/OU/P87EA0KH2CJeHI3ehSa7U/hi7KlaO8oc5rDoMiX/ftDP6DqHdjw9T1Y9NNh6uIY9Mfd1vCgCUtlV7r5pcQ9DDVSCONprYsfGYrKy7uR8tGnvquWJeRIXsUidlNskeWCPa+LNFcbBW7krkCcxuCTJqftbCOmefibZRcZ87HkT/bT8HtWD4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: drone
      namespace: apps

