apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: apps
spec:
  encryptedData:
    client_id: AgAZjTeSluu1tXye/EJcSvvygdHPVRmawGFjSvCsqjTcZDGmlLcBeVJL6VpzUs4AX0Kvdm3kxDO+VOGT9fMcXj74uKha6XgZVj7k5EtIjDgzXARzQkZVuyJ7u22/GDA2CWtwZbFHLMNyliuLiK8/E/CFM1bMEPLq2o1seyEx60zlKCoI6CBnfUe7vypjQrmgUK+vu4Z8Uc5ntJCTCAOkLKuBAuzw1tzJ8VbkNFa+ed4iftn43SHYGWqylmeQC2EmeeU7lWIx4OMEOsnj+jyN6VoY7V1t+AwqrY3Rh/0C1XNN0R0pKQnoeGMICxgR4fN/FFJv8ITSz6Dj+QfjvRkR4tJDiqzbYS90M86fAMl5DnbRJVnU0guBWKW9OblbW3yBMMSeHcijINUm9jy64+uy2aXMeEpJAGIXvjvYkKY1H+U2D8JS84UR3EYPg1jzpz0R97ehey/12HqriVuUBkugoaWAQA93MepvOqHUt7YcgrRW+L+Q/Vw5pq56+RyvQE2D5IAFLKnKOAuyO9MwHctRmNKpr870XbDkd8oE1ZMBLXfLaEL8rwFO7bw3fvubDYHP54nXaFG0dt2JsHlA18nSmZ9Jc/5xpwjrEKU9Z3bjc+MpPqaki046atDSOBa60qYtRsNSgl+aJpT+VFeYebOLS9rmhnMwnmrIy1JyrCW/3aE8dNRvDIARPTRViKQhGlb7qQ3Crr+B7G9Ogmj0hnHJ/zhii5WS6AUVVJBICDC7d+IpVomYm7A=
    client_secret: AgArnFdNlLB2hZ0rVUVj2NLGOi8xDWWjEovEM6j15AAv66ikoiTudyMFAMVLlIOL0j5h9oQ6yvYemGVEkfiQPc50F8UxT/I2SmzYigw8WDgV35SEaitmZWmheUiR5djchuVRjkduPESBNEaTgRizREcOAl51kOeVpIMmXcbBKvLJCTjVpPq5ky/CV6Qc8DZBAiGxRTsya/oZEu6hF6BCKH9S1LVGixdaHrHofLQIUCe2EPPi3kMmKHoZrYQJc+sVbcC+aMXfJfla32BaV8gMWz0oBOfljuFW0lxS0sWmH7Tkp/gQ9ACQ0hWjfVZbF36WuIfABO4cbzIEMZy1RlMFNp/lehek+TDjg6/KWySyfvL2fyR4fMrf1ZZccFNMIo5aH2puGZXtDPoZxCToglXjUXLEJHjZISs95buRtvUyLvNSrCcsdZaOo0YZT87xhkSUFHYIOtOr0e++tUUX9AQSDBEM1jZfVlkpjOe6JSrKGY58iYOjK08okVPd0bIySXQ7H86svTxP50xP4Ew4ymX2AQEg9Ikxs3OnvVWiwVelV30RwQt1eLFiIZV0jK7d0zgUv7ybseizAazCKS5PA2nvCZdUjOeaZ/SYt6Gqyi43NQHM21rxTcozvM+83C2Spfyb9xY0pl2oAAJm5kGiOlSt1lKOyhd4j/d1vgmW1ZJPq9iBkFWP3cCpVIrw1i1ynBYczHmVntAFI4MDHEECXCzGaD9K1E7OZwK1jnF+itMs7zdRntqJpwXGpm7uieR9mw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: apps

