apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: apps
spec:
  encryptedData:
    client_id: AgAEPPqa0xQ3AMqhGHlOV6i9ND1lygxhWFxgpQ++9N9hC2h21t+wRJCWTUB7bIcKSK1whpPs0fRWDhzC9d0JPZoHuTNU6bpdJXLBE7UIUq1lBk77q3Tk0sQwKJ0vA2XZ31V6rxXs1vTH7/gGQvMgAjD3cIrn7bidCIzHBK1uUsu4QZQzVif+2vVXIfvZoO6IHJmuuNmqEpL7muPr/fphkVFYajK/BXoEux2MavEHXGn/G9VPWhEobSLhQnwxrldRqLKInx4efWbJscPUqSLzXGo85efMGWyVifMEKPMtQT9hYTsB/Pc+NLRf2cNjT5uxaiK/BFv66F2Og15+Vu9DVec+lra2R79f8/FnemM30cy4e+Lu8ZONnDfFGWqG6j9q+3qJ3HDN2MfoqpAo1PHQTc3E0NRLwh6cHhkrJuY5EBBZQYegWXvBBsOVVs9wOY/RyI1ltvkGSbNI96v8J1NSbldEPmzANv5deVWRQfv0snxK7Y87Vgf5VYWz0JGMxD/wjFQbvBLi5o3efBD46LAAK0XJwDMNFGZ/UzBqh24RDmbRJNlngS2p0gU8D1WsxmLcnfyEx/zza5Wp7UNtk6ftxqLonAeLl2mcX0yvbKN43eUxPHdWPV859fs/UYXwSHzdcvQ6c1J7XUxrhnZAVlgAQbf7nXEM3EPNIAecPmutuhGCr/PPZkkboAGNmTbW9rrfDuK0/Bp9T3onkmtrANYJISKMm36RFCr5OvscVWwCPC2aahFujUQ=
    client_secret: AgCZNI0tBBYsAcJ08SL7XgWxI1laZPDl3LCVCLl0eZ6uYigCMtoGeGrHpzW/fmWNHz7o+l35nFkkX3mx/qW9cf/w866c7S+TxUlUlLnjFBuHz1w4t64iUdbL3etDCPM8xc0LTL4XlQaQLGHEQmsbfmPCY9oxQF704cgXA/FPdzGoA9M7dpD9x25OqWfc0pZy2mQRGsWhAymL1p/fsSfhDWrp8ELiszKIPfXW30EUGKBpqRf5rT42rGBFNjACufHM3CpuPQatZTzoEyvE0+s/cLNxhMk4MpnYCSbZrUQNjeQr8L0H5XT8gUapCIZPwRjddAk4toNGnwhC1kh0ks4gx0Qe6iA/qzNES+kiRTSmEVYfk4VnmpKJ/M1//PpN0f/rH3Ix8Y3rVvheeiz13oJ4pjwgeaROORWE0RjfeH/KcvPoHwgpw47icwLzUxSV3xIbIPBo6DBnjv3viD5eCVVI9iW3stgccakkoNmf/z5lV5ithwWtkB4gVhrlRK64kXsxeNuTTlO/NXbIQyOna110QT0WRYgd+xTj/npoj3ZxgbEnXOJTczcyMxn8HZw20fOrQKluf1K9+opxOhE3LaCih3PSWOjU52ZhORxvSoBSRhYtYYYPHQ8H4uNF/aDcFenbVBCptE9QtAbVzN7CTcZ05hnQzWIJ35iafhlnF5FYdTesrjuY5+gXHDk+7OTW3ST14kPLIIdEuY9AHq7P4rbN1qyYHlxwrUCkx1k2WPpW/wxzl4l8f8yMt3gj89EFBQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: apps

