invoiceninja:
  image:
    repository: ghcr.io/linuxserver-labs/invoiceninja
    tag: 5.3.35

  env:
    PDF_GENERATOR: snappdf

  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        ingress.kubernetes.io/protocol: https
      hosts:
      - host: invoice.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/invoiceninja
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    redis:
      image: redis:alpine
      ports:
        - containerPort: 6379
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "45 23 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: e28d1ffa-e0a5-4fb5-afa9-f3e3d3fb6a34
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/invoiceninja
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config
