apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlyoffice
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/onlyoffice-documentserver
    repoURL: https://github.com/alex-phillips/helm-charts
    targetRevision: HEAD
    helm:
      values: |
        env:
          JWT_ENABLED: 'true'
          JWT_SECRET: errWbW6vttFFSczLo329X2omeKrvX5qLdahCGB8yVU
        ingress:
          main:
            enabled: true
            hosts:
            - host: office.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
