webtop:
  image:
    repository: ghcr.io/linuxserver/webtop:ubuntu-xfce
    tag: 2021.11.07

  persistence:
    config:
      enabled: true
      retain: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    shm:
      enabled: true
    downloads:
      enabled: true
      mountPath: /config/Downloads
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/docker/webtop/Downloads
    shared:
      enabled: true
      type: emptyDir
      mountPath: /shared

  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: wt.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  addons:
    vpn:
      enabled: true
      type: wireguard

      # If the podSecurityContext is set to run as a different user, make sure to run the Wireguard container as UID/GID 568.
      # This is required for it to be able to read certain configuration files.
      securityContext:
        runAsUser: 568
        runAsGroup: 568

      env:
        KILLSWITCH: "true"
        KILLSWITCH_EXCLUDEDNETWORKS_IPV4: 10.69.0.0/16;10.96.0.0/16;192.168.1.0/24

      # The wireguard configuration file provided by your VPN provider goes here.
      #
      # Set AllowedIPs to 0.0.0.0/0 to route all traffic through the VPN.
      #
      # Pay close attention to the PostUp and PreDown lines. They must be added if you wish to run a script when the connection
      # is opened / closed.
      configFileSecret: mullvad

      # The scripts that get run when the VPN connection opens/closes are defined here.
      # The default scripts will write a string to represent the current connection state to a file.
      # Our qBittorrent image has a feature that can wait for this file to contain the word 'connected' before actually starting the application.
      # scripts:
      #   up: |-
      #     #!/bin/bash
      #     echo "connected" > /shared/vpnstatus

      #   down: |-
      #     #!/bin/bash
      #     echo "disconnected" > /shared/vpnstatus
