paperless-ng:
  controller:
    labels:
      nfs: "true"
      pvc: "true"
  image:
    tag: latest
  env:
    PAPERLESS_CONSUMER_RECURSIVE: 'true'
    PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 'true'
    REDIS_URL: redis://localhost:6379
  persistence:
    config:
      enabled: true
      existingClaim: paperless-ng
    data:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/documents
  ingress:
    main:
      enabled: true
      hosts:
      - host: docs.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
