paperless-ng:
  image:
    repository: ghcr.io/linuxserver/paperless-ng
    tag: 1.5.0

  controller:
    labels:
      nfs: "true"

  env:
    PUID: 1000
    GUID: 1000
    TZ: America/New_York
    PAPERLESS_CONSUMER_RECURSIVE: 'true'
    PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 'true'
    PAPERLESS_FILENAME_FORMAT: "{correspondent}/{tag_list}/{created_year}/{title}"
    PAPERLESS_TIME_ZONE: America/New_York
    REDIS_URL: redis://localhost:6379

  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    data:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/documents

  ingress:
    main:
      enabled: true
      hosts:
      - host: docs.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    duplicacy-init:
      image: alexphillips/duplicacy-init
      env:
        - name: BACKUP_NAME
          value: gcd-paperless-ng
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/paperless-ng
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    redis:
      image: redis:alpine
      ports:
        - containerPort: 6379
    duplicacy-backup:
      image: alexphillips/duplicacy-backup
      env:
        - name: SCHEDULE
          value: "15 0 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud
        - name: CHECK_UUID
          value: d880aba1-cb4c-4134-a0d1-9d7e01bb7f5c
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
