---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
