apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  project: default
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.3.14
    helm:
      values: |
        primary:
          persistence:
            existingClaim: mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mariadb-ingress
  namespace: data
spec:
  rules:
    - host: db-test.w00t.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mariadb
                port:
                  number: 3306
