smokeping:
  image:
    tag: latest

  env:
    PUID: 1000
    PGID: 1000
    TZ: America/New_York

  persistence:
    config:
      enabled: true
      retain: true
      size: 10Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    data:
      enabled: true
      retain: true
      size: 1Gi
      storageClass: longhorn
      accessMode: ReadWriteOnce
    telegraf-conf:
      enabled: true
      mountPath: "-"
      type: custom
      volumeSpec:
        configMap:
          name: telegraf
          items:
            - key: config
              path: telegraf.conf

  service:
    telegraf:
      enabled: true
      ports:
        telegraf:
          enabled: true
          port: 9283

  ingress:
    main:
      enabled: true
      hosts:
      - host: ping.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  additionalContainers:
    # telegraf ping / dns metrics for custom smokeping-like grafana dashboard
    telegraf:
      image: telegraf
      volumeMounts:
      - name: telegraf-conf
        mountPath: /etc/telegraf
    duplicacy:
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "45 0 * * *"
        - name: BACKUP_NAME
          value: gcd-smokeping
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/smokeping
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 1b4c1bb1-5172-4a3a-ab66-c1c15a76cb5b
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
