vaultwarden:
  controller:
    labels:
      pvc: "true"
  image:
    tag: latest
  env:
    TZ: America/New_York
    DATA_FOLDER: config
    SIGNUPS_ALLOWED: "false"
  persistence:
    config:
      enabled: true
      retain: true
      size: 100Mi
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: bw.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
          service:
            port: 80
  additionalContainers:
    - name: duplicacy
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "00 11 * * *"
        - name: BACKUP_NAME
          value: gcd-vaultwarden
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/vaultwarden
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: f7a54103-fbeb-4747-be31-c1e1ef3b83a1
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
