vaultwarden:
  image:
    repository: vaultwarden/server
    tag: 1.24.0

  env:
    TZ: America/New_York
    DATA_FOLDER: config
    SIGNUPS_ALLOWED: "false"

  persistence:
    config:
      enabled: true
      retain: true
      size: 100Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      hosts:
      - host: bw.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
          service:
            port: 80

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/vaultwarden
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "00 11 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: f7a54103-fbeb-4747-be31-c1e1ef3b83a1
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/vaultwarden
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config
