xbackbone:
  controller:
    labels:
      pvc: "true"
  persistence:
    config:
      enabled: true
      retain: true
      size: 10Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: share.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
