xbackbone:
  image:
    repository: ghcr.io/itscontained/xbackbone
    tag: v3.3.5

  env:
    TZ: America/New_York
    APP_NAME: share.w00t.cloud
    URL: https://share.w00t.cloud
    PHP_UPLOAD_MAX_FILESIZE: 25G

  ingress:
    main:
      enabled: true
      hosts:
        - host: share.w00t.cloud
          paths:
            - path: /
              pathType: Prefix

  persistence:
    db:
      enabled: true
      nameOverride: "-"
      storageClass: longhorn
      size: 1Gi
      accessMode: ReadWriteOnce
      retain: true
      mountPath: /app/resources/database
    config:
      enabled: true
      type: emptyDir
      mountPath: /app/config
    # secret:
    #   enabled: true
    #   mountPath: "-"
    #   type: custom
    #   volumeSpec:
    #     secret:
    #       secretName: xbackbone
    #       items:
    #         - key: config
    #           path: config.php

  # initContainers:
  #   cp:
  #     name: cp
  #     image: busybox:1.28
  #     imagePullPolicy: IfNotPresent
  #     command:
  #       - /bin/sh
  #       - "-c"
  #       - "cp /tmp/config.php /app/config/ && chown 1000:1000 /app/config/config.php"
  #     volumeMounts:
  #       - name: secret
  #         mountPath: /tmp/config.php
  #         subPath: config.php
  #         readOnly: true
  #       - mountPath: /app/config
  #         name: config
