xbackbone:
  controller:
    labels:
      pvc: "true"
  persistence:
    config:
      enabled: true
      retain: true
      size: 10Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: share.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    - name: duplicacy
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "00 03 * * *"
        - name: BACKUP_NAME
          value: gcd-xbackbone
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/xbackbone
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 8c0919c9-6db3-46e2-b532-dab567177f16
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
