xbackbone:
  image:
    repository: pe46dro/xbackbone-docker
    tag: 3.3.3

  env:
    TZ: America/New_York

  persistence:
    config:
      enabled: true
      type: emptyDir

  ingress:
    main:
      enabled: true
      hosts:
      - host: share.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  # initContainers:
  #   duplicacy-init:
  #     image: alexphillips/duplicacy-init
  #     env:
  #       - name: BACKUP_NAME
  #         value: gcd-xbackbone
  #       - name: BACKUP_LOCATION
  #         value: gcd://duplicacy_backup/xbackbone
  #       - name: DUPLICACY_PASSWORD
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: password
  #       - name: GCD_TOKEN
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: gcd_token
  #     volumeMounts:
  #       - mountPath: /data
  #         name: config

  # additionalContainers:
  #   duplicacy-backup:
  #     image: alexphillips/duplicacy-backup
  #     env:
  #       - name: SCHEDULE
  #         value: "00 03 * * *"
  #       - name: HC_API_URL
  #         value: https://hc.w00t.cloud/ping
  #       - name: CHECK_UUID
  #         value: 8c0919c9-6db3-46e2-b532-dab567177f16
  #       - name: DUPLICACY_PASSWORD
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: password
  #       - name: GCD_TOKEN
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: gcd_token
  #     volumeMounts:
  #       - mountPath: /data
  #         name: config
