---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge
  namespace: apps
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn
