apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thelounge
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/thelounge
    repoURL: https://github.com/alex-phillips/helm-charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: thelounge
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: irc.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
