lidarr:
  image:
    repository: ghcr.io/k8s-at-home/lidarr-nightly
    tag: v1.0.0.2255
  controller:
    labels:
      nfs: "true"
  persistence:
    config:
      enabled: true
      retain: true
      size: 20Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    music:
      enabled: true
      type: custom
      readOnly: true
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/music/beets/Music
  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: ldr.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  initContainers:
    duplicacy-init:
      image: alexphillips/duplicacy-init
      env:
        - name: BACKUP_NAME
          value: gcd-lidarr
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/lidarr
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
  additionalContainers:
    duplicacy-backup:
      image: alexphillips/duplicacy-backup
      env:
        - name: SCHEDULE
          value: "45 09 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: afd42e78-4b68-43c6-be5f-081fca7c0f3a
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
