apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/vaultwarden
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
          DATA_FOLDER: config
          SIGNUPS_ALLOWED: "false"
        persistence:
          config:
            enabled: true
            existingClaim: vaultwarden
        ingress:
          main:
            enabled: true
            hosts:
            - host: bw.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
