---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
