apiVersion: v1
kind: Service
metadata:
  name: frigate-rtmp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: frigate
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.133
