apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: frigate
  name: frigate-rtmp
  namespace: apps
spec:
  externalIPs:
    - 192.168.1.133
  externalTrafficPolicy: Local
  ports:
  - name: rtmp
    port: 1935
    protocol: TCP
    targetPort: rtmp
  selector:
    app.kubernetes.io/instance: frigate
  type: LoadBalancer
