apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/wikijs
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
          PUID: 1000
          PGID: 1000
        persistence:
          config:
            enabled: true
            type: custom
            volumeSpec:
              secret:
                secretName: wikijs-config
                items:
                  - key: config
                    path: config.yml
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: wikijs.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
