goalert:
  image:
    repository: goalert/goalert
    tag: v0.28.0

  env:
    - name: GOALERT_DATA_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: goalert
          key: encryption_key
    - name: GOALERT_DB_URL
      valueFrom:
        secretKeyRef:
          name: goalert
          key: database_url

  ingress:
    main:
      enabled: true
      hosts:
      - host: pager.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
