apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: domains
  namespace: apps
spec:
  encryptedData:
    root: AgB7roYXhiOmefxxBSZ2n+m9GkHdfqlZZ8BGAjZK7syG35qKlyfZnnWNYU1a85hF7hCseW+XzpLc1FFeYuwmD70+gG2fUXsyE0YDK93g8MPy3tldmFNA69YkBf0T2yykU+5jwGqY0gDmlzTbom/Uq/aIqmmq5PqKDe1UQSHvwEl7/3IY/dkfwDjP9ILsJuoDVINrS8bN07rN1JMa66UXbi/EyUz4NMAep6b1u+i5rFj3mdWVsqafL+7+rlfGCfwOXcI4npUOJ5HlhGKR8Mr0E7pgujBQZQnNVX6Xwfm9AZuz4Jy09kzOf0eqDnBPdNC//yR9nQ/ZiCC1OmE1i/zD1uBSTjg9OuTjH7xscQU+MvcMJW8dcoGxzyC420fR7AKvo3gbM1DRLysCcsHgOwLWKIS/gHQUqu+3ikdRjAWkjhukH/P4RI/S3LhYHvHCUFLPh/pYYVr1vf2Nk9ZXzFOp9k8D11w5B13pKBM7uvQwBmeHRzuy0wzQfR4GLeOCWKZaX1ZO4IwJpSnTIL3JUbbJ3J7Izt/SzXacvVYQHZXt5mj4q2pWgE4yLpqfuaMtD6NnmA4c46usDFF9BwXOowzvhAGDj9wOViYYNQkzgghXXTrCZLHm9SlDbMzgS37gb5i6XxfCVLpCyo1/5hhiugKEWZrZ2CwouN7MnnTAUMrK7zQCnW3s0GaWbvKSco6rk80QG4mKcY1zfbj08En4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: domains
      namespace: apps

