syncthing:
  image:
    repository: ghcr.io/linuxserver/syncthing
    tag: latest

  controller:
    labels:
      nfs: "true"

  persistence:
    config:
      enabled: true
      retain: true
      size: 10Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    data:
      enabled: true
      mountPath: /mnt/storage/docker/syncthing/data
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/docker/syncthing/data

  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: sync.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/syncthing
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  # additionalContainers:
  #   restic-backup:
  #     image: alexphillips/restic
  #     env:
  #       - name: SCHEDULE
  #         value: "30 03 * * *"
  #       - name: HC_API_URL
  #         value: https://hc.w00t.cloud/ping
  #       - name: CHECK_UUID
  #         value: dc718e37-926f-4f73-846d-0b918b051fe4
  #       - name: DUPLICACY_PASSWORD
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: password
  #       - name: GCD_TOKEN
  #         valueFrom:
  #           secretKeyRef:
  #             name: duplicacy
  #             key: gcd_token
  #     volumeMounts:
  #       - mountPath: /data
  #         name: data
