apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthchecks
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/healthchecks
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        controller:
          labels:
            pvc: "true"
        image:
          repository: ghcr.io/linuxserver/healthchecks
          tag: latest
        env:
          PGID: 1000
          PUID: 1000
          TZ: America/New_York
          SITE_NAME: w00t.cloud
          SITE_ROOT: https://hc.w00t.cloud
        persistence:
          config:
            enabled: true
            existingClaim: healthchecks
        ingress:
          main:
            enabled: true
            hosts:
            - host: hc.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
        additionalContainers:
          - name: duplicacy
            image: alexphillips/duplicacy
            env:
              - name: TZ
                value: America/New_York
              - name: SCHEDULE
                value: "30 01 * * *"
              - name: BACKUP_NAME
                value: gcd-healthchecks
              - name: BACKUP_LOCATION
                value: gcd://duplicacy_backup/healthchecks
              - name: HC_API_URL
                value: https://hc.w00t.cloud/ping
              - name: CHECK_UUID
                value: 233b56e0-a601-41ab-b8c7-54d6694ba973
              - name: DUPLICACY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: password
              - name: GCD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: gcd_token
            volumeMounts:
              - mountPath: /data
                name: config
