apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: apps/
    repoURL: https://git.w00t.cloud/alexphillips/k8s.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
