thelounge:
  image:
    tag: latest
  env:
    TZ: America/New_York
  persistence:
    config:
      enabled: true
      retain: true
      size: 512Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: irc.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  initContainers:
    duplicacy-init:
      image: alexphillips/duplicacy-init
      env:
        - name: BACKUP_NAME
          value: gcd-thelounge
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/thelounge
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
  additionalContainers:
    duplicacy-backup:
      image: alexphillips/duplicacy-backup
      env:
        - name: SCHEDULE
          value: "0 8 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: df625b66-f4f1-4e7d-96e4-79ded0074943
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
