apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/node-red
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: node-red
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: node.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
