apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snipe-it
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/snipe-it
    repoURL: https://github.com/alex-phillips/helm-charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
          APP_URL: https://it.w00t.cloud
          MYSQL_PORT_3306_TCP_ADDR: 192.168.1.91
          MYSQL_PORT_3306_TCP_PORT: 3306
          MYSQL_DATABASE: snipeit
          MYSQL_USER: snipeit
          MYSQL_PASSWORD: ztdrvqAdQYDfxbUd
        persistence:
          config:
            enabled: true
            existingClaim: snipe-it
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: it.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
