apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/haste-server
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
        vpn:
          enabled: true
          type: wireguard
          env:
            KILLSWITCH: true
          configFile: |-
            [Interface]
            PrivateKey = 5pUWleoH2fU938H9c7qWyhTFgNd4Q8bnz7Hv77e3pK0=
            Address = 10.65.127.181/32
            DNS = 193.138.218.74

            [Peer]
            PublicKey = Yph7Oo28maPFDw/yJI5Bq+gvGE5qRqsYxt1lJ97vviI=
            AllowedIPs = 0.0.0.0/0
            Endpoint = 198.54.130.82:51820
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
