photoprism:
  controller:
    labels:
      nfs: "true"
  image:
    repository: photoprism/photoprism
    tag: "20210925"
  env:
    TZ: America/New_York
    PHOTOPRISM_SPONSOR: "true"
    PHOTOPRISM_HTTP_PORT: 2342
    PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
    PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
    PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
    PHOTOPRISM_READONLY: "true"                    # Don't modify originals directory (reduced functionality)
    PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
    PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disable built-in WebDAV server
    PHOTOPRISM_DISABLE_SETTINGS: "false"           # Users can not view or change settings
    PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Don't use TensorFlow for image classification
    PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
    PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
    PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
    PHOTOPRISM_DATABASE_SERVER: "192.168.1.91:3306"     # MariaDB database server (hostname:port)
    PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
    PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
    PHOTOPRISM_DATABASE_PASSWORD: "0C4xmt5bhu1rFEcF"       # MariaDB database user password
    PHOTOPRISM_SITE_URL: "https://photoprism.w00t.cloud/"  # Public PhotoPrism URL
    PHOTOPRISM_SITE_TITLE: "PhotoPrism"
    PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
    PHOTOPRISM_SITE_DESCRIPTION: ""
    PHOTOPRISM_SITE_AUTHOR: ""
    # PHOTOPRISM_WORKERS: 1
    PHOTOPRISM_ORIGINALS_LIMIT: 99999
    PHOTOPRISM_DISABLE_CHOWN: 1
    PHOTOPRISM_DISABLE_FFMPEG: "true"
    UID: 1000
    GID: 1000
  persistence:
    config:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/docker/photoprism
    originals:
      enabled: true
      type: custom
      readOnly: true
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/pictures/Organized
  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: photoprism.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
