nextcloud:
  controller:
    labels:
      nfs: "true"
      pvc: "true"
  image:
    tag: latest
  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      storageClass: longhorn
    data:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/docker/nextcloud/data
  service:
    main:
      ports:
        http:
          protocol: HTTPS
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        ingress.kubernetes.io/protocol: https
      hosts:
      - host: nc.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    redis:
      image: redis:alpine
      ports:
        - containerPort: 6379
  initContainers:
    config-link:
      image: busybox
      command: ["sh", "-c", "mkdir -p /config/www/nextcloud/config; ln -sf /data/config.php /config/www/nextcloud/config/config.php"]
      volumeMounts:
      - name: config
        mountPath: /config
onlyoffice-documentserver:
  env:
    JWT_ENABLED: 'true'
    JWT_SECRET: errWbW6vttFFSczLo329X2omeKrvX5qLdahCGB8yVU
  ingress:
    main:
      enabled: true
      hosts:
      - host: office.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
