nextcloud:
  controller:
    labels:
      nfs: "true"

  image:
    tag: latest

  persistence:
    config:
      enabled: true
      retain: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    data:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage/docker/nextcloud/data
    nas:
      enabled: true
      mountPath: /mnt/storage
      type: custom
      readOnly: true
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage

  service:
    main:
      ports:
        http:
          protocol: HTTPS

  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        ingress.kubernetes.io/protocol: https
      hosts:
      - host: nc.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/nextcloud-config
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    redis:
      image: redis:alpine
      ports:
        - containerPort: 6379
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "30 05 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 397442bc-235c-4442-baf4-a1686bbd5220
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/nextcloud-config
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

onlyoffice-documentserver:
  env:
    JWT_ENABLED: 'true'
    JWT_SECRET: errWbW6vttFFSczLo329X2omeKrvX5qLdahCGB8yVU

  ingress:
    main:
      enabled: true
      hosts:
      - host: office.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
