apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: goalert
  namespace: monitoring
spec:
  encryptedData:
    db_url: AgAGFZ4vp6Hf70/UOtzDU2a+ErgSKGUIyIf18SzLScY+gDuNhMt8jXvuyTtXz97BFqwjm7lvvxdN3XdYz7+EcPLScfQaF3seZcSKiUcm+yVw0qCITlqQLjwjJ/UOfJKG+OuKV4XmE7lkYbJ5Ur/SOqY3eU0eZhik3CSKQcyc1B8dSX+NKuuMLVOSf4lp16pSItYBOWqt4+uMeYVconeZroLAUsUpLMs0T1uKDqsj1GsRbyBN3yXx79SbTWuD/yl0pyJA+yftawmQB4sEYMbD3Ly/1D6NZGOVKPYYUvVuZYCzlIoiPq/Fq0eKX3upEjdbAbkGTYzuziC7V0Fypgl35jPsoEmYZws8rVltadd9nKv3Yl/uTJalhbQy1EiWxdZ2bfObM6pbHjt6mXYwKCWNUnNR09N8x5PBT5469fQ85R297guqoU7/YWalHgZv5MMgSz5/GqkXKU18j47LY/V3ajZR8zHGg3kIsy6GK+pXJzPjBcgxZNtAiDR/3rN4PRkC7EXa61Borix8wE4We4Gb+9brvOw0b+801j5A9ZY+5oVwgdQClHTVlbajxfvLgjCD1VIM+cIBkWWCcWp3/CC1KYatJ+f40xu2AAwkTD2Eo/cAlN/QLOkJiSCXMabV8x2C4pUUfTHM+jO/eAX9WEEGIvouo+Jq18UqkAmAA4xw7880voPT8Hds7jIBLJi0CDSMNghiPFoc8VAAuIS0lc2LoVmUaV3K95e9/1Z8RiF5DlvYImiOB1IeeQOqc6bJMmx2DxtszEHJ
    encryption_key: AgCE/qhEPkpTkLLlwyLKh14DT1gn3xXcwPndOHdIhRb3efm18hRX+X6SaKPGZ/mVL/gyIIECR34INWZPH0x1sUnJs/pVJKcH80Nuu7vQtEJrvAgX+Vim4U9HBmLTpgekP5Z3WjJf+x88Enr+jN+S/szCnSGMgMKj/d3/k/U7oALd3h9HCD+WuZ9/FSL1OLPpqeaKHwRfH7Nw/3RjmuLt53rvIy4+aKltXSxhdQpvUih6Y2wT9q5DhyvqYg4dFD1fj95VQfsRYFv41ueYzN1cIdLOf/cI4EBT74hXLqWlAhFqaff/Jux/K3F2JmJjnQfWc/SovYPPYYFKaBLAuX/eyqOJdbKeE6TQ54vcJjZ6WD0/s+Oi6tau4bCREHdVqP4NSkEQO7NXMAEIXbCbFABoSBMS2eeW3JA6jcAY613pWkG0qR7DSv/DvhiSSzt4JSD/MtiTOhLDXOpli9XT28o1VYne7qZw2DTEsl35rK+P5QBideFELS9GjC3FBO8J1p+Dcpa9wirMOZvIFoTD7fZDK10vSntz14y6vBJhdIMLCIhzy9BHxmEk2RCuxBElrflkEvpPLF4S1Z5Yd8zjQ5NbsxgzQgt5L6x+G+RJb2rvl/ZJF/S1GuYBl4hJbvlYE8N9OKVjgJzPddOdlhYAkanrrYTXQ89+ZGOtQKMtZh40micvkC4NQjv5PYXcjMGN0+5Mcl7AEyzk1P9nVYrRA35sf7LPYS2AMyiX8WugRhhFUx4CZw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: goalert
      namespace: monitoring

