apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgBTYJ/hJeX4ybw8HSF5aw2oWsZ5myZqban92XCTmUvIoV3gjh++FXFxK1DbsnM4x9j50/B9I15Zq8nuEfT2O5nfAuf6V1O9u70uUbOGO3tSrrMso4ZGbFlXKfzb49t4durE72hcE1iY7rke9KcX4M9EFEkJoTvbInDbzeNOcF0XZVu2WMjSejlxwbs5FPelys4CPob7+eP4Gx2tl5NSGxNnjBMwYz8OtCGR+dS+c5vV+GbnXLILa1LMsISP4RMmE1zDsWOa1eKOET1Ts8EwL/q5zHBNjk2fBgp7ZOigXvQ2zVK57CjtK/kXxjvlNbtDBSe95WqJZYpNf+vnWO0B4oUSbjxe8yO51fiRgajbSYAI5dXfw2jAiN2B+NtqWvaxU5J9lIJCoi28bYPLPVdEMKe+CFgIqZlEiqpJPlmbNsXXGs9Oy+a25Z1jakAhf3+T0PTxaTzdvhm1BT/dVHWpD0C6DVz1CgU3ofK4psG/GUa67TWBilwLlL9eYaWpIiHJO9binFBjxmBLi76oEk433xL2+eOLnA5Z/hh6fkicECfq62a20vBHixZD8oWPnTw643ezywrHh8hh3orR7vLe0Cxqy04/af2Tk6nvtH3uasjveKtb+SmrnXoRIaEeY9S0bVFg6GpmbZ508+o78hzxx2pNya9qemUY0CMUeng02kScl2udhgTX5X+4YPasfvaUNQxJTbAmm7UOw0FyCGEq6nvXJkmCw9jBBS3CVlXMqNIGpBmyr1A=
    adminUsername: AgCDL9ywxEJ5mB2UYiAljD3aFpIFlG947LVhwz2xo+OYVgcrfdCWkNefnNAPcJnsw7/SQlh1WMpuSD0oYd7pkRCJx9UAw//KHX0biagWMQO+zQ5AJp2nppln/zVumO/CC5Uyj1Eylzlo3wcMkO1gZNhA92oe1EvZUyDNqtpDHP2EYgfBmWUyzsQPhkVgw0qj0ifLYsLvXgkwqEtBYNqDVWdsE7iZ4bEsRE9OhwrC5vwBL52OYiU5QO+P0Wt2D51r5kgomhsq0N6v8RJLBd7xyPMyELv3UhQFTdlycNEX1ry0c/pl45cpsmD2YXkFmda8GR7VxFK7N165lscwBuI+nfuSufkkBZN86IAnuJ/QM2vA+rKLep13YPfi3cb01YfJXZTYZOmWdAyFzc6Z0SSiqxEqnPLk8ra3BhvlyEIpgQkexE3L0HxtYGSv7T2lG3FIPcBt5FMxgMvH4MQOJxtff6NU8hDV0sV7nRgY3PQPQaTWfJ4somoDifEsfSJyW5ubV/LmA2ubujRhMHr94G7z/meslt4VK++nr5bcC40OCvBc0b2z4WB41E6UV2MOfIAo3gCkqBDGnkz8zYISqRMmdZOIAcO0a1iUBdlFGyuOz9VtWkVPhtK6QJ7ttAgaW1qPBiekJ4W+zkPmoWElOHauByMvpNetduBDc8Koi7oZLt0L0DNeZRikeXNuH9GCZa8FZaaDds/k
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring

