apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB7Rdd947Hs//R9uveXHD2KAPOQZYAw2GlEvOU+MkO+UmAFeUi5DaTz+qh3QGS/br6RJtBQy0f2UI8zjUdsnC4XnwxVq2/BPyDnahJameQsMa9cc1/5Bww67eG6Ik2BlLXeHHsUPexXmP9EtI5I1ypDN3oiHZMvPDzWVH3baNGdX1MhxAINOvm8PtPMw/eGxrl2sKnt3UvE8ztH9B4xqFEH9FTxGsyCik9ggn5jRka9mSWvopIBhFoYFNb82051hyz1wxDakGSZsApjyTPJPA8HlOUFrFuDoYlnTUAkqxdQ/6ikK2xrcYI9wxRDlEVOYpkUMeCoOUKP5NZU5TP0Qjo6klJ4MwAdBj8I5W5E4oyegiG9i+apAFejPCQAgWplF9XnOjwPSy8gAY0HxOrtpyBrEWU6cHu0iUfUxd5fazfJwabw527nYNC1iLnBjjjVUdEztYspdARE1SQBZCQa0dM8SKKTpn72+i8kVk1BgLTjZXg4Z7v3K1Qr35y5M4L6A0eJ8/XFFw5lXNnaP/WWKi5rglrmVFhmElb9IGew29/IY2ndRorqjPXW3xRHLzJqCjxCh9tGkTDHQLmP8y2j2JdUaU9Uk6nR7fa/kDKubfscvbz7OMZaoEh8rNysMIENq25mO2rOHKCu8uIMiEgoZgSfYZfwyggCxBJrdLvGyIkAiWEH3uVGpWOpAZwK5y99tfqNN7fRupATT4GAmvePLn2T8kBlLt29EPEuwCgrf6cgXY6vgUs=
    admin-user: AgCVylCng0G0r8dxJJ76PNkBPTpZysPq0cM6KpoJ7AIqi5RyfyoK/4fBY8WB5gaiAQKPN8Dx/yam3EFDpOVruGIeHisYauIwawL7mK30eo6cLzRohcwq0h7RibL4uGLyjHimO5d6rXgoLIw5cUrUFfHU1lblL4s+j9cHyW0vx4jZ4iUMSRxrf6hkuhxqxJIOTH3C9aGiORPQUfl6whLgoqn2pz1u26BUzlVyD9obRxW0qDRBNiWCk3htYirU3YdfnwBOHIo36suAu7pr5B+JgiGTujZEMTNZZ2lpUO4rvdNs7i8CW9wOPmeVN3JvwMcUlvuV0NoA5WCGyawfIk+AFt6oNq45rXJzy83bGeRH6+lGSWpA3K+UKmSxk+sdjpGAJTGYJ0e64a4cvNtTH5RODVPrq5YxUqzQIuuP8WtD0RNX9VvemKukh3LGYHlvk5u+MVYfVl6RrK/Qd6xZp1ntdyvBnYimYaIxXUgUlwnVWXcvbGAPcO15AXdKAwhDM9esF5YmHDWzzpicks4XtWeDfw8TpROUnQLnrWXxyDRPnKtCSMIQTPxq1KwE53VwBqOZRkpW7zUCk1sHpbHn6521wrKPEwSEzf/5YNpfy14tG6MNAQurGmxltmE5kYvc17Fk3Rt1myJrAWbrobm72DIL0exkb+1ZC1D+TcgiIp1gI5+I4AD98cOoHWqOqoxQCxiPl9bfdy5E
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

