apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA1P64LYnQ1iiN+MAGnhEeB2oOOB74Qh8ybWRJw5KAuMta8O5bHgECxPnBNjB0krVbMHTvd1rZF+cySvCHkQoTk8KeaF04WdrHgixbnmCTEmu4tcZDeQ0R3pSJBuSSCHKeHzq5vYy1ABFkiIXq8ipvGN3br+tooolWZ2FGZCMzyYgBS0C0v/cgAvLYiwov/UbQ+5DciirUaQQkPgubvOVtgg7j/5+roRPa70E1ap8+HHXi+zyZIrZ0IL43P12dahvhRFDgjh7cHNcxoHjdNLnRO4on2fF+U64kXRGPwApTbUuU5+59IpLn3dP9KlFP4JFZjHjh8a3+Vv5AM7ZyCeTSCbOUqAUY73tXVW54afO18BsGCP7/aVwakiblRdtVBoCc8yJDXToO7A47K3qsXc+wOuL+MVI8U6dTvuVZ5AeHR2V86p6wGbJYRxFf4M3/vaBMMKlAZDAVZKqHH1CdnyhRbnUWB7/7UAInQrVpJ8Y7d9QT1CnlvXfInVP5RsS47cpU3Xh7W81mNTD6bZGrcauj6tUo7dR6B8RufBNPJmxifqki69/f9rOAgHnwmguVowauCIRDcdlSOTVhwV/ukI1vVDD6KxvFWH7iyd55bpL03VKFOI+5T44O0ISQ3mA9MUJLAqckfCaIXPbkgF5akWfkXY7s3a3yh782/n21xR5QtV+s9sm5pi/71QcfzM3tL/UKD/SEwjQlVAoy2wt7v0o+euPIiq1hxi9Yhdn8jjxd9BmzEes0=
    admin-user: AgB/mYxE3Bi03h+Yn6uTUyJF4tmbZJ2pR/+9m9yvUr5MSa7FfHc/MvPLsOxaj74Vwf4iFtuueIUj6iVAVq6mcDyn6ltVScSJ3Zq92WKUOzsClmnShkKD5Oe6JZKGyUE/qZNgTkSMH8kBagfXbYbFvaXAP3V8+EwGxqbS4gPzTz7gq3D+49lXt+U7hZA4Sy/jpPRvoEGlyakmLZIn1+SsZuLdgcKV1uMMK42KVJLmEHaSeVSfPJTs+xPJjcAF5B/WejrjxLiDv5Q5BZA2wkVj7coj6wpP9kxSNViYOMhxkePcSLOg0Vv7zc73IhU+zFF6BkuGNK5gRVvJzb0naPaNhbmIg2ivxTIDayzGXvRFGNafmVI8Y7bppjOUzCf7e98PbW7lNP8JpDnbWmOL6ZuO4ykd60fO8BV3vaTS+m7UHOiCILm+0RzM10ptLHkvDq0d4VY7SCmDFRo7RoBji+qUUyeQ5Zav2HQBgCEMidKEUYc6Lrj/EJ3xlRvR90c5bC+PESenphEVk+H6zRYjYhzXKp2yT/VEwCiyMkW6Ao8nmF2IMKoNokves6BbIsXIP3oFHNpgVLZWDt27dnfURv1qzzGCXvn6aLb+1de7LsFRZPT1okW/HT14ukt5p/JX2cGNHtc/qJbtruP6U20M/JOe5O2CjfsjYsF/QMvAkYiStAWUqCT7WRx8xcEW3NBtlMVvVJSQrsjK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

