apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAeKCJ0Z/2L2wdtcgB7pZORTpnWGzXc3cPQi9B0+Pa0ySw9JTK6cxLyubBTLxKgx4LzV5IaGpNEFRyDn8G3HwbpDxHreFjSweaad816CDdgWV4Y84Y8D/K9So18nE+3GgnreXAh8iO/pjYopJ7azcA+JQ1ZqJK6eqGmnVZXuEQcZ4Tbp0keZvzO5W2EOayjo1QiDSOKEOnZKPzKz+r9qdS6hdQMqrjVCf5xVX35kIg8BcJ/lzNy/MSmf6WGSrHUU73ysvA8n2D0zf+pOVBWqgPjzvNqjyFVnTUJss4Jq6+y6PJ3exlBVYTj61kpC51a68x1P4Hg0QOtcXP9OJtAO5HRnqzo+edyBg4lY6aajpA2zXbtoi2DLpnemAPVPKoEntG7tjVD266urm1gEw+sQ8+xUTHL/uIwrX1C/3rFu2ett4mVtlzgXRKlZpXesY8MXUZI5VOIDgAootHJ47Ho2v81K5kv7r/eRWmW4LtOLEF6O8Nj2kmh6dju9AtUjpKm1Ofj63rvbSHgxP3CHeKH6krH8VF6cK6LHFdW/nOvUiGVUHzANQ2BKqWmzomMsZxJaTdwp/L9H5uPi4YL7ybkq40UbXkk0amsTO9d8+y5tz/TdeFAkYSMACDcZYi83ug3UZQ9vsFGhWfHDzQSSwtVPb7c8j6trob61UpjARKETCc4c8003HeBVHSDiU39yNuI6GiQniGWC9shw+oy26umGsZvC5ojiDUs/2VU6pqrY004WRaCH3M=
    admin-user: AgAQqD1ssidxt7jMGZJeG2TuUKz/tj9HqGXMhKN302YvplbVfuNamYbuH9057iniaTejL9L4hJGifiYkOvUFHqVkJx21BtjiXUsUB7rmhMGa0Nzr6eAJx6j+8SqMzEeQq7eFX+YQBCY43kadMe0Q/yz9bXBglKPe6uKUTzN9EPmHTv8V+5FdQ39z2YRK/XSxdMBFpDeZN1uxF4qAc9oEebJHboBmNvSVXWUzq8+Y1CR3ydD0koGJY7SdLJu2pTKBC7HR3BEdJWfOmolT4nb8mTB6Mc7+u5DccWkT/xgLzRakAdo3Ef7I7k0cyf/5+PEBNKxGhZYwxn6d7z42hSIdWelaUaZqRpU08g46elLW1XX3uAhAE+p1bLB5+xkiGOHKkCcWZ1OI5WKDw/YOpKxXx3wJcnlf1Tn1lJlR53SMl/3Nu2Dhpx87NG95nUsdioAcESQOHtPBroN7Kr2m8KqhU7EmOzjv9tiPvYQh8rWsKF/p00VSPK4HllaoymIamFqxd40As++Fcmt20vEPTnsZxtPLSzi7mIxIdRycNrYp+yCm3Axc6Bfq4iWy+HewHR/BVz5qjDv0BxzurAZExRw2TOLE3A49nItKBywq90b3qkqDHhYWmxKreqoom6y9n7ECbPsfn/t/Oa5qOPkrCAQ30F1phrQd9AHkxKroSDZ8Mpzh3Bd+2JTcmMCaP/XO7jDxVd85UqeP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

