apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    adminPassword: AgCiAHDlLR0uLARnGaYMR38j+SgYZu8zH+QG8OzJRgcil+WcxjgedUjMjonILhqDJfpZpuqupTFKsyfm3rixkRup+NJoj0K+ioekR9rylPIyQwQUKkmHYw4dk2qo1o9rywbyRrkk4eGcvX7Yq4YpXXKDoJ2zu09cL1BfVxlV3lsj96/IAHZOyQKS7odEY66/0/4AkgYOfYIu8rowPGyG6KuYfcZf3mWifii6fe4pn11N3EHo7yEKyxUIFmc6tvTpZr1JLPFF3+akls4g6rI9p8MWZewqyHackdvcZ9soN7NkYaLDVDJxfHe7qQ0i5IS8OkGgNlcM5nN4GsbGCjAQmGgJZJTusipoZ3ibICR0dcS/tmrRoa7k2jbjCnd5roS+UF3m3g7cu81LDF6Wosm4HugR8rty+rIAARbca+RYORbvG2IbbMd26AP1OCMonWmJvw0oh2HpeC25v7FezFPLmsHYmzNETTTgAKmx0+3yZmZGUGzCsWWJSPtPPPILR1pgM6zd8TzZANi8IqhysLNY4B2o73Ul0AhpcS1G58H6G86YZv7yIuE9fM6HqwLRnIDqdOcUD7okS30yC8l05YMjC4vaFFlAn0jwGt2uQkjDsQEoVOx9pZQChzmpRtzAiwtRm+8VUyoytJL89WdvshnRBk5cEqudTJpkhMmZT0jPfCWSr4cfH5v3NOMXTMDbnNSrib8aPRqLHn7weSRHGEQVLQz0m8KwXbYzW8k8dwfAcgSH0keVY3A=
    adminUsername: AgAasjavhcT2Q4XQvdSYDyhU4heU8Wyo9ps/+q7k2RBRMjXAYTgCYveh7Z/aLxsGjDQJnE5IlgyBtuACWqajafN7O1JU9SAbsogfG+sz0hfbopYcDdpknWOZtx27e6043DkXKZhrjKgUVb18+i0Uik6PPUbcQstcLCm8mAI7vf2wrofQL14eiWSQm15ttjjFQaTElBD/Kvg36MTcse+/u+HjDEakv5DLaZxmc8OBkXxscDJJzWYi4iwUrwYRLoEX++zHDxWtlXt/E+uV35oik8JAgdMWrkKFOrXZteWgdgbhv1hwSOL6TOHA4DnawXjRjQ/H5knrOZS8ZZ5/MwL71fHmGzayZBfyLbGPN9MEFgMExJmIYKnaXgJHqrwZu6VMolgox8YXmBjHwycMjp3jKdYOef51WF1R+jvOt8I2oe60OT5ntH/0OG0DKw3c1LpqfEhGEB8m324gR4q11QLDK0qpf3yL7ihlNluRovAQlz93WNty5w01tsiFmLDUwTwbBiYMEFACwDfp0AF5p35wcVaPX+xFZNCKB+JILewo6fOOo4IzZEUMaspUW+UNPhzkgCY8Bx6+V4+E/qdWehFZbUVvkLJ/tOYpxeNZWqF3BO7381gEuc5k9Mo043BaZ0iMyaELFuXf64K18HvQidfBIqY/iyMTMU+uuR7cZNV59QD0pC1CqzWkxOst3kvGQD29JuRMOkHJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

