apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAiNAXQCu4AoFbO8QY75B80WW130EgKylI/4TKedyq+r52LbacuMWVAM/wBd3zyk2YGV7XjOI+nlzJ//f5ArQ22mStbGxSPPMREQxJNefnZQSal1K+IExGzif/OihLIa8eu4H/1nu8l38mJzGUhKhhvJfJqRidWhTPpIPGRHbkay7kmqx0WqrTliEU/2Tu7qZuE4RsNqu2oTo4fKgi4YdsxPU8myYFXWlWn6iOU6mdPjdDm+2Drm6NMy00zu0Lcw4pzL/hB3ZzPI8dsBfGnRS5shMZqt1gP6SlbW95en84xh3eFBfeXDBvGAIoEtge7+sDoQn9dQK4KKJSvE/2X1x8zRwR6n2wKh+MHlNQjQmkivR0BtWocAHXXMk6tEmkRrI+Z49dqbgNKltdKGzobe6VDpoBt+9cLC+u8P0nVIYll5rYkJJoattM8LJ54+38oRuYGFR82Yn43HO1hY++4u3s7siNgMxxK6CLmbj76NGkiPSCA5PRdWb/pnUhSWxX6TnGQFdLGUKwQ7jUEf8McFzjzsSJauyGUFXe3hffMihSO4XIV1q0B23dI1bmaqHEpzNI+ykLs9utG3yZi0/3dtZ26t77WGFwKABwr5u+1RQ4CfaQmNAVWO3YpfWXfpvlhrbUe3Z0sf7jVSmkdSB/LoCOs18qVZHl7SUQylm6dUtERL4a8rw69u+rVD1aqpDIjY3PffqPN/AhJnowGCCKKNChlDMH7+PNkdqrjObhGmPsf6hYaG2k=
    admin-user: AgBV+EDgcYoDeiJT7BNJ1hEiCQhYtlSfIek6S0YHKq291rNzM+tNoM1ZCGysZ0SKlY4PJCoW/3XKLvPCZmofiDuVSmlekcRq7u90D/L7lKBb3aXkrzbJ8KzvAvlTi2tsP87keKL0GR+lboa0VEFJyKlhCZQEFaSJngUyfRGcP+V/jJnR7VjP3HS2sXmrMEwjoWHexEKv951GCKxpaMju5aLFIHesVKXzaNy3wd2WQUpVrOKLi+9LgB24Grz1Oatr75/VxODAiDaK6cJvA3PKzrsHI4ElzcORvcWr+x1314HVm4HtSzk93emBy6V2g1LFfGTSjzwJOpXncDe4kyd88LGd6eYly/YR5n8W3UHtZkWAVbWL/9ChUEVY0GDoTYQDJk/1XZ1zIWAYysPzB3axuNHNC7tBaD8DhlXHjomssBKeY77XP8tO5A7Je/mWgS44DT9lmik+xOXzDMt2N393zai5F7zwP8trNr7+MyJzoDSVMklWE3+rknevI7ZL19ujINKZOyE0XOFAj7wQ1I4+YGojyw6cF1xhFL2T1BAzqO654gh4WTf/Nyf2jRSw9n9zcKOamRcKoN5ADS6KQ/VVc7BAKH2KUgc0dx75xXf5dmbo0Ya+71glB8QE3Nx7WDwswn089ZaxIDucQLYJML5l+4iQqj3Cwxo0y4m+pwIiNJlQ8AfzdPylYE0xgQ1n+gUpYLn+fa2M
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

