apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCk/dvD3NEwpS9fs8qaZKv+08nJ7OTuA20dLm7sXCAqhSApz0nzdPlJHS+XKTuyMY6OTqJ09W5XBIFyZRUtieZJ+5rMFX6B+laUtH3EJQVGrE+LCNfdaxB7wFNdd36weEhZyIUjgaEg1kgwG2Vz4MzKUhx3QOsMGMlRfJCHOqOzmXQANbyFzTLfZjeAsyEOmziGlsPKL8Jgsb1IqrqPV005DT7Vk4Oup97hZnbEZzN5dvHhbWPlJ6+8yT/wWh4dLsSTZlYLOuATCngTkcg3/Etc2JyGEmSnYQ2c/8SxGeOJHZ2yXECSR+XNko1iSjtYIZzcru4S6UGmMtmLuQsYwMZbUvLFEkDTaBEL7Txp97ANv0kubEoxk0+EGJO1YqPNVQQ/kzbUbqjn2+M9hefE2HjFvIcXQ6uDXkhxmW0CSloKoUEKGDUX0wociQMyvMG1wSHUomXsd1qs5Ln5bfmntSHN4vSV4pqx2WNifhtup2q1WDisYHRjO0B6dt3cJgVPoYi8FKIcy/y10T45/mqkn1OY8aWpmKgJAXiml1rh5N31yc431yAdAksd3FbXVBxsXa4hkykgY8ddHxYBDiPvbwsM3GqZ69KeQj3UHt8WHrVG04xZ4L0nYu7S0pcBuj50Fj1iir9ufhG47DE6mV7xZKO0LBgUa7b60Ke25Qshf9Sblhby+OMp3wj5II7WIKZs5CssBinUv+1eFqhj2/UR+Pq8RP7+PFf6luNRXMUE7i/J0UmRPNI=
    admin-user: AgAG0gurHnhyc5S/8n6d2crsulOw5BRTGqIRu33ve/N9fF6n+0/vgYwHbzglIgaQ2j5NSbD6H7JUojUHJaFevBQnyW3+wmGhr6fbt6UtjtaX8W2N6dIuhfuBTvavEz3+tyaCoJqyYHwR/Qou0SSm7wMhdcjOJ2yEWupNMaWKHBn7AJsB/5l9UNxh5W6FLvFGDJOH8j87TWuqPZk1bDr/tppquZTafMThqnuH4h2o5xRf9eKc4NYw0B2WR+KQAbktd2wdK7c4dg7qIn4UPzDKJBwFFdtGvYOUAoGhZzxq28JbReTuzOU651VxkLdmw9eMV6VhGIP30+tRRFSYtVDBA45BLcer8N1WeQ8VsqaKdMu6V7WVB0XbhfowsiIeY17bEAkvhU5iJ6huBuaIL4Z+xqHdP1KPIEkkXJorlOVGgK+xaYISEmae8rBmLmPIVjywifb1dQ5DNQKiisqMsyUog0EUr73v6PBFt2bCPSpCZ6LT1vUnKXsk0HVM9ABEsVdKyy4Kqy80nPJuKAsnPT6PqPXYTyPIsKNfPb1/PY4ya5s+oXd4LXTcK5mzeJaNNpUitZ4F4VksvjouYuQdJ1li3/OKjIgX4U+lwJRd+JQ4fvTM51rH6Lg53cbKjfczhPrCGoJpvKoNnVl6INf9vgjCIbmwV+914K/NvQOFTTrGqCh49h0BrI9UWxUJS7QHGo2oW4NciCpj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: monitoring

