apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: monitoring
spec:
  encryptedData:
    loki.yaml: AgCUjgRBN6PulrtQl1HK9k0aCGWg2kkkoMZmNZgSL0on3CoqYNNOskXxImtFZrSV4Si5Zb8IzhWO1NzbH05kYmi4El7BBT7ac7nTCG9fiiUBIIoc+p+AHesyBCYROnG2HtFxKn1ym1mQEN1GcBnDP40Wgd6AMz8v8D4W+XkBe+MvMjnUlhdQqZBEHnA3bU+yzojJ8HjSAiT9mIVmG9ZqtmjvStAm9gMkQJgsWJU5eTMxSmO2OFXrxQuVJbhzg2r7oLVjapEgNPYnOYZ6y3A3uJ4tNVO8B00PaRVM5wnaRZgIKiXs4VzcNh898sRDX6e0Is0UnkSblO8pqxcjIN1NqFPHphSy/E3WRTL4ZKUKG2T+oCsrrcMWZScZ43cY79/qJVlzbyYymLZer8nKDELultW6v/mkrYw1SNnFLbEUXVfDrV+5Z9ODFi3NdxKtPUrk1h7DBte7FT22OqSzBHXpT3UMmAOdZliHYsrb1Nck+WNc88Do41cHhn+rux/SAlzawo3yKCrFzZeNWOrexwx7mk7Svy2ShwEAdcek6SCuQzWN2qKkn9q5Tm2SEsQYDmsMiccAi2q1C5hqnDsq+o05Hp01a7/QyEESths+6yN55COMDrub1NlOdrDZSagSVeQ3H5tvSLRZJ1UozLJUSK7uJi95yhLxxqkzy8HU46k+Rua1kwPu8yX+FPTzvzuN13KI1XmidL24sB7DuCQTA1n2JFDwGLMbAJZfONWd1/LfZinfwgtnKNIGoZnbf1+YUV90jjDKZjfwD6OnhQlElHzZwtfoFNBe9qJrW31TTsJNvtPc6kSoE6utE3gSujwVQK5DY9w6Qwprr5z89jDKK4/LfqTj5h/UwyiiMjtHx/taFGlpTN+fI9eRp4k4NuIsUHdZk0icKGeODhKqwVXlvluYQZNTKVM0K/1ocXOGjPEiJVpL8KdJOjXFTXwdYHPhE/lk9aHyiO7MLyOKVweFcffQ7JuJuJY/SNxu6OtQDdFnXdr92nHpUUBa9+94ySSfV5+DSz1Uq2QxGcpmaYUkIeWL92/e4G5mnTZqHM/r14Mm4DsUZJU6Z7hffP4hk8vuCQKeO8pXoQAOjkJAC09vmdsIB4Zopx53rJpH+sK9aSOyBZM/fq0trpTozrTdXQztvSkOrTHrRTiaKqOyuC2V/zrvZg7XMZgy/cnt20dRngn0OAT9z3vzxU9kxXVoCmqbVVBTYMToih/wOrp0/4e72dT9b/VxfkjSoK3V7eXlgys7L2sPcSe8IWKRx0NDN5zBZBJwyhc65bnjI6+vqh1AIQG1eObwPDOBN+8/CanowvnF0eC6Q5ePVj0yQnLm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loki
      namespace: monitoring

