apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: monitoring
spec:
  encryptedData:
    loki.yaml: AgC/VCyEsNDNzf6HcHNkxeFbo2ys6kOMffey70AiPxPCn4Ny3rd1yNBBnv8326BnlkuiuVWA8zBkH+QBLdgYqnOr/4brJ1AV2aIvxTRxQy0wy3KBMi5FcbtDVRRRLOHLpRWW+G/nXar0/7Fc/QROJMw8UtEUPs0+N6NLZp0jPmAodP24YONMuiSnn2yG/NOAZXDP42neLAr7jWoGc8MxBpUPRWOjQEgNBcMBa9X66kPjuoekQkMctsmlsg25vfrnLEiKA9XEEN2jgglWuJsXPL+fz3fyJpeUe7Vavm5upJWa0VzOL0QhqCZJwwjU6GwxeZo22vK6jyFv/lH223TxeoKixAVVhMB7qY6jdVvOlOWsJIZuzUvM4FtRs97KZJfp5ThA1hARSq9kDpT0yuH5mV/hA+QRcKODJI41qt9SkZfmyPzIgBmmkmJDcqQcGU2B7TQeX/ME4ar17mY98y0nlkXFtUfhgDluMt1pObiB9WzYQhKfI8KjsM2cW1mENLubFwAtPyTj+fE48hCrqpGsEmylVViqshuu8XGi3FnCA6Bu2FobPL0SjKVCyTTa4swlFz8UmftG3ND5Gg3dZW48yDjSnLKwv1TSssGj91l+1fQn9AHvZC09mVvqwLMNgVCEQoLfB9QTZeKu+GdTgwsJmz+QA4MZ/YDTf9kAUC49G7EJ369HTDXzgJTziNunZvWneRkQCay1kAPOr9n6SiwP14VyacbLJZcbVtEKNv2AAQ612uf1ZIbxa282GSdHG4AXStv6q2vym+H0lFeOPkHBGxmcoLSTvIoKM7EmucTMayZgCOYsbjTrcvMbU4z73md6aXWQ3aUujySlVWn3pYFftbQIz7aHMxquEpdRAMFD+OtHiskevOuNNGRtISkKbVI6O2lqhyU9/QFO9OLzg5ai2oeOUY04fLXxTyCTCvZ2VpWfOgNhaDfKHRjpK6t68ac8+atzOWFSdrcJhFK8O74xrMMvSLhHT+YTJCH25s1xgYyReYmEpSvKIpbVF/Kj28slyjSpM2bqAwHk38iF3JmBiymHmSjpfhoWvcTZ58NoUO+uZ2mCKp2IZFp610fPLvT2FWQOnVewIqTB0P0lGT7M0c7snug7c70lph7YEwqBSt2nYJnLksrkX1ZoGmFYb4UESi6jnGV4wM7hVw5XgHW1NZt1oj+o0vDG9rV/2aNk9T2HVf2ZHHn5MJ0+GWQGtJJohdpSpTDWMsvybmYV3yfnA565SHJixbZwaAR21LMYCCQvsBdUAJ8MgHN0y+OHK7Cq/iWd5SvQirTimhycwJs/qjKzNa+dbXkdLoPrDCR4s5ClVRiXOuaoB2OE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loki
      namespace: monitoring

