apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: monitoring
spec:
  encryptedData:
    loki.yaml: AgBplZf4o41BvrFvP06UKDWQAQ1ZpDrytjy/dNX7hpXW7Yk92ZTDyImhNkDjPWLgzNmnV9enVC0DDSjDsOhPjikCI3/tgjSSl0dGurKt0tnbeEl3NuM/NMfmcjRSIzt293CY2rLDj3UFElSN7/EmKwUVuwmIG80E4XnbmToRtYM6HxNVIqj0xLUOr516HtMjhrdqQG92cSM4OdWJg2lbUW2RFbHR2FWm2yfO/kiDZxU+1uRReA+jGSBd3WxwLHgoi2HYco7wCCABpYtoXUDdU2KyZOxSqClgVF/LY0241dTuBs30IVZGDvrF0JJksn9aIa+K5nFpnJvnYv9uUH5RCml38jW/XrdP67K7WZXMyEhpV5LQj5FSm3AjUwP8v8DFQ3bvNo5Ml6xFj4yrBhSvcSeVIbproNrpNr0Lk5nuyNGW2Mlqw9K5eGyQkFEtTs06AJbNJcsLJ2XXNfjHO/bTwS20yvsRO/UOvdNGwFPsj2rpVwPMd/WUH85oK+shCp9oZ+zS0J2c1WITTtelm8CtXmqgYW24PhSvw4FHwUHIPQeS/Tfa7KhNWrVANbAnZelHyMeW5WGDFpUSpXAVeRrSdACM3siagEyJzJEgHoL/1dazbXrDuKeva76Kw0I121pFBhyZwbcs6PZ6b0vneoMu08TI9E7SxlhZNXX7JFwZfRWLe7NlEJNRSqmm/m8oHHGzeAzcANokSY9gZaPg1kzDuSUIpV1Zt+3Mxjp4aMF7cuPgBNxn19sBy/XK55OQz/+o8syYfWjvm0XQ7mznDFmVD/sfdAUFOxZ3St9XLEQB66fvBVYHPrU215aVpnr1QbhTO1x0FwKr4pBoei0te6vmK/S853Dn6bZqyBdQm6OaImOUFxWSeuqWq1acfOnu5UvXcG2/utoQ5B7C9Ur3rLCm2a90Y4NwGSd2UCvc39CoIVxYmtBe8vnj+SZ2WlXIHSzvKIvAl+2EmxH8ui3px82leMY1FRBfslkIVhOurnIT+jUB4yiJpBE1NfhU1R/1lFjdHAFIcVmi0Vua68NIhhoGPt8USguVVr3UYB+GUSpWw6+Giac2nqHTRsDck02JtG/wnduQzWZwgF5zvuzDga2DFSCDnnl55ihQ0Nml90C8hyfDOcYV6N0oaH8yUrz0BNOiko8TopOdO/GFBMvR/CMKxltYjQmeR5Td5wZXjYGM56vo41JZZ96e7UeInWJlxnfU5Q+PCelDloXK6MO8cK3UGZ94XcOc8yDuqKNQ+u3stNXVwbecm/z7XKK6Dc1isoASCPsULL8Nyg6wu2SxcuHCL4YnP6EIIpW5BiPmkCaQ3FdBCs4ksSDwgaLq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loki
      namespace: monitoring

