apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: monitoring
spec:
  encryptedData:
    loki.yaml: AgBKcv/ph+lVNE+bZJ/Y0wLH60zwjFodMeDlpeRmGliHtes8USX3T+NF7h1WG1qcZTpzkb/+CdNBnxNcq7ajDopHZVrJZvdPU62TkyAUY/6B/b4feNHV7409c5FaM2ZYCgxlVuI5eYAD7cyMnHEiqIwvucGcmXtiTy7dDHIaD/FnT77U+aA4WDErm53/8B3DUXuMGEKwzvep5+bn4lEXuX6fcuoyVAvgys2DZgzTWoA6rbSorAPJ8hoLDR9pZZaBjoFBAnutsWhO0i2z1Bdt3ZdsQ9WpeTNRR6YaxG8sv36gEU+qrC/FySo6eI/Z0Z/o+KbBr0qDW/tj87YwC0zIf80gyHw/S6/gnzKaIiFv0gfaP37kR0bB6Ky9uzgvTH4xnqiRjyDYnLbBJb/aTw65tFHa6x3V8EsSUsIP/8EeABeg9/hz6Hh5URWPt7aHO9ImpiTmLNeAjTpAvoGhMvxZyrWokVdNbHZ19jBg80QdxEidpqc8N3VmzDHSIMtul92ZF5Wc3RHS3tbUienKTYCg0ZODRMhaVd6Umlwa/ujwpqlX7+1QebAfde8e115LGoTc4PrHBXDv8qSBZv3oZ6GgbIMvRmirAOXyijdTr33A7ZflEjJPCFgG9VqXyu3Jes1s4HYP+l7EEJW/x30CSMQkGBHQeGCf1yUjopn5Au4gzicwV/EVkdgQZ5a7bFgocblciQ4f/FaXx3J4r4zMVQJ/l063d97xq7Xrqrwt+IkKNy8QhKffyCvnU4pM2nlX80srBd9AlY5ECggUWSG6m3KKkWSRG9KvlKSyKHShKjD3xjV1GjQYbTO0HxID8/h+oGUnPrhOOJBLN+tn6sLeoIkh4gPeffbjdVRz67qGLKnO2IgvUTawN3YHDaWgqAmMUdfn4J2ingC/AjOWYoXSKwy9FQBr2d4s057mcVApv9XfVefXBpH2l9K5sFBoirrB3FACAYNTB0D1JNEJoFNo3JCF50iJId6/jQGmrz7cUEv9RQ97G1qXbCSWlKU544lJTs1N4VkRlRrjgv/DL+BfoBj9dth4vaDnxCHXFzQ0PySXlZz49cyzzjXUzTM4xhNwpkoi+5wzd12KmeLQcc4+n7ZRMtn/9lIkvt3DahjVpajdCDYq/nz02H1+R+HLUx7Vsp5NZsJVChppXM06JP8JnfGn0bQrcc6bBbQKrgbd5Hrc9ZWrPl4mbKR1bL13GJ5SycWlwGie8yEJlEpDao2Y+A6HmkM5rKk99G5ogjA6Qm/q7FJeyKas8l4xbq+v8uE8pO591ppXkuglBalFBv/ZyqNyoKjBK8062kbkvMSM+DDsBEighcRudmD5yJaO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loki
      namespace: monitoring

