apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: monitoring
spec:
  encryptedData:
    loki.yaml: AgAigzeYkfGpyksyMc15iWQoaxG7XZDW3zq3TzjkYr1y50lmmneDpUBo6shx8aIJTT4VLtecb76VD+xEutFUM/vJsGcFiWoKwobElgRn/rKYcFl5MnsS1tltenwJKSWPJvZLKsO30XKTnNJ43ahEyXCwn6/g7oc4AMTQeRShmxYKDdADwNLMt8ybz8Sarvuy+MugGY+6Yk1Z8auuwWVWgytOk4nMuDkgJ3eE2OP/3BzMCEbmjBGlq/EhszM1lgIp2m5c5CF3ru1yHXh73jlxBE3nShdJl2Fh9BYRR1Ane1mMcyF3J8YS9unM2XqjK/Y5vFPwVfSKswlVEz/ia9BpWySb7HyTT2g0echr5Zip64poHMG592trWgDU+YB190X8rJHKu8WVuvf80nqoV9B6P5PcCSUQGW0UdjFqhS7VsPlzgQu16fSpgJjK0eFBCuvcJkkM161CmRuFmKEts3dgt3oFwoj9ECTpfqQiPQPFz5/Qmoe2MNXe3BQX0l85NleCVbG+X3zYrXSq8A1W8kc8Uiwj/q1y2tWzOKnRtrYVTwEdjzAc9asmkQTs2oBaTmDAW1UsAkbfzNeyKKbgg+d4mo/BG0oooGcFmE13f/Wrm00ZmFZAajnNpacqztutwY4jtpm+aTQpG0RAQnMJeub/nuirghJuWNQczbscoiHLMAFUslWVXrknTBcSGG1BSsMTXSReRXFTdb3L8pl9d/zk7g0VuDCZxh2/tk++DX/3t1/aPWFQoPGFJT65Z20q8yaEkq4pqjSzyRcdj1kIok7EjU7Qv0vTYd83bKQ95tymzSKdxS4ZcaewP4Uq0Snz+rGOma4JUte3GaKTL+2LgQzkGNbz+IIXGwBJran3DzPUjHHtmW4RpfjObxRW40bTpG1AcMZyjEiE9NivBwHfwzjfsy1zbxZL+RB9wK3+bG8548d0kN96R49d0nDSgBwqAksWMi0advAmyyeCqfQXxwx+3q2ogXhLZWpKPMN0sd8YBH7yhP18iIA0F2OL2yJ/qHV5NfVlCf0lgVPl+vXC16RCQ3jmx3NqmOvk/CSOVGACkNwDCp7lnRXx5z/8+vpMzoj2Aa5oyva48lLdP+ZMYunUrAIBul+uSo91b0vSlE+tGsAFhpMPVBS8gKvYuMbZdAblXej8IfnJhMDNUxHjAw5vi1ffSmWoaBeu5EkQyh+hlX6k5YVnN6yEbnh+i1eWeti3+AOjpJyl6fIdmquAbSjkxy9SV0Dcmr3b9NJspWGEC8nzUunpmB4iDQlg/mWmVG2UYhJubNsVtKKkLfX14PQs6SifJBoJaZRJCTPF5KcwlZ3fjaJWrwIoJHeM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: loki
      namespace: monitoring

