apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBvaW+oGjow7enAxI+v6BaT8toxl2tjtwkJYnWMtWKph2uYfT6fUmzRG1Z6R7ZzlURaC96qZRzVyy0+gD1NuZljJNBgHqY1thQMMjN8au2B4jGGKyWbsU3vw/Kzo/T44Dh+rpJvMEuQ0iZf1JpDM4ACPIZpVmJ2dyb+MG3Lysz6riW0LMSya+6umtbbC7CS+iIP1fF6VWYv/GRsGRozsOe2QvTlg8fAIgsdNTkmBGescEaYie3cBdqTLSnCB7xWg77uWaF2773LgCj7AD7uHZ8wlKPw1d85R3qzUjBY4f6vCILqMOUjnA74NQ1KFjMOnZ3HI71fn9tPd9P0VYl52ZkTMrPUpJoYWPMpFsCWOXRHNuXHLpH27KCrfzC0q0YzGNkwof26G/8N5I2WvaByCq91RahMm5T+NQu5TMmEuoPCM5NsMkO3ljPhg3v6m3q8quU5I65xuoEpwsjtlzfo43H/t0vuqnbs6icM1D91+OwEel7y4qBctmOVgJgZaHRXqfMWWMtcxo1VZynV2XLIRYGZX/PX2+kmG8cM0aVDysvEl70TOf49/I1YdoFfD802PkYLR+oIAEy3pCEknNs2Tzv5RE1O8tORKdrLZzbx6gcwTXblC9ZqwfDfNsHPqpY05R6Y3cTiPx7GTuqqxjHn7bGkj4Dc2wntNvJvB8mGwqq7HggIVfdZEvZltLMjgAYVkzkJ82e5mw2OJ97byb5RkCCcwM49gStRptko4uB7CWPCwc9FWn7UBXsaFRLJh/vX8wkT25nCWQDYgAhXsuJrlarMUZAagi/LgyyaGTxk/+5q+VEcc4sxR6QnE6cT0Kr5ezGhz6wQrRxX9Qj/ggmChkbQxSkdIQaogzy9lpv3VDdS9h/rzcXHAyAv3nAMP0FyEURsZdhbLvj4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

