apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBGjeKNdnnUgsSQm8iGnrTbDD5Bq+U7bV8rqvrzieXt4cGnS1IpecGEmDufop7z2IWsho80/gvhJ0ZC6bX5xlvygjV3DsQxDk1h6stHG0FLBI+JRanwwEI2jrWGawxPn4x3a0pi9j+b2JEckzqVJqpfBijZCWSnNlY2qHf5SL7y9i/ynRublQkcnGnlq1QyGdIgiIr8v0uLZ73cEVMnXOGWd0X/ZiYu14nuzNZaENxkl4YjWrpDpBdMAktYamPriTfbYnSE3p0iV+hI4ryajkhO2VaqDJ4BtDU7Wr0teKFnjnf9p2KGxkBqyxiDRoGCZVl3f+7xmb9Kf0e4fTH3wbfi63NBbKtBIcK0Rmzc+gQlE9MCqFiBlxP76KmsRJSeUIOTDVnxHHk1FhSWgu+GKa0AmY5RWtipWtwwrHU/U5M6aSt6qBjXyTWhXSg/V7kAuLKkHus6gs0Vh1oJ6UWXvRSCFHoR4FFZwRQZcdzr8PvxfZhOHF2FEvtrxTnzwm1VQAQ4jBZMB+YaQgF95m8iajLBnfb/JbdPSKyzuq1DDrMQ+J+txbqUj6pfXl2kCzql/HeUxi7M1PNfOIyuEJ8bkA9px15ee1A4je06N/ZwsBcp8AKu7+O6Wk2ci5k+WM0hKUtU8PGZ/ODEy0VpqRR/Ip365meW2izVDZMOmeUElAG4Q+5JVKg4f7DaNpdKnnZTuSfKvin+1rTUxWj6zgZad9w5WWivC0revxpEqewpZXTK6SU79WabInKBihcJ5xTK/0FF5yzYvFrVLJzGuzrYKRfrxGMQQdsPMEnLuYoFxpGuOPrLIuWHPWQs/lxlnDipvOLdQFo2Nt7p8aIkpmmvYBE93tLrnHjq0/pWKTkK8Pna4JZosT+Vjw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

