apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBmp/6siOtkiPnHwyrkMMEqx1LhYOM8Nmjz0KMC6f9FA9cwuQotS7DVBJR4/LqDZIDJYdJU9TMz2N7p3lC7oq1rFz2qEoJMuo5R25IwVOMbS2Zxvz66LYslJ2anst6Z0rSRcpmrqx1gO4hGMP9OP9CkW/2m0NfqkDtsqBizAaaDrpoEPJdtYoBVlklmH6AwFnQwbPuXsp2s3U9ayeuJ1p79+KuhR4HU5V0/nzfAPa9vcigGzHChTgBDM4IlgzIEUNcWHo4JMPRa8lzHO0ZYpD2rANJyr4VOZmxKCBiqHcP1bG4GpHIH+vFEYF0EnsBURfhL0Yp9xe8FNEqu8TEytWZvBQ+Ull0gsVFQxfXkRtnt4PqWm1T/LBM9So8iAOxtGcluykgZChqHjJ8F8cX5iZfPdcmFVj8JPKex/IpSt9YsMaIglEGjnszWliWdBKRYrr0FVIV+MMl12ldJe342BjMIvK04dlJt2ILp/anINdA02E1giz7DBWCXOiRJXcsbYY1WzOJXRGt6b6kKOf5DYnaNzJkeUG0W/s3SfiRFPEQgwTQy5Ctp8uflnr42InzrbGYyhphzf9qVDgv6zpasLglHCZbnc/0fmTtjVemeiy+tkNl/Wq+j3SOoXFyR97mF9ykLBxXnHdnf8+6WJX192iSJjjVw15faYrGC1EI2oo2w6n2lbEejdWmAp2BJdQ8ORHeRSwNvpEd0FRUMpBDu2UpTtrx+0Zw7+t/kPE2U86w1Ro8UDYD0hBhOmSAyC+KS/wy/Ate+gFTN97q1I80oDYTb6nyfKwQfK87J04rb65h3JW/V/uNBgczeoUXTJlhgW27nSd0XG+cFsCAfjiinkaAGP8y7lrHt/HDcjF9FcBa0GANapavgvrMg1lHGEBY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

