apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBBZGNbCMF3GwJcF874vgdNMeu94rlC1YI1Ql37vgIRYFwVFEElzYDDBG/12kD570fyTaWMGk8oqUW8EIomqZ7QF7bqwQnhG/Jx25XY7KJruAGZ4IijKDjp+Wfsl1XOC1QkxN/DJn2FyX0ZHtcGIGNHZW4Ed4Vi0ao/osklPfroGrEBcX1JBc/Lir5A6mdN5z0CMNhyRcVVNeGgecGsrljkIw4qlSPoOggneNEgCNoX9qUQK7HG9eNbnrCsGk77cOOGPYKbobpsGc/IEfSHCT1WMUFUt3242ZwomYNYJuq1YUgTY0GxiCQllYEeVuL1uGX0lhmy7TjVSfFqXEqeElmEuCnj3vPtFktYp7JeVgwF1Zl1IFa4gptELxGp1FVWIU3NTrGdZ3ytiiUR06sdx4UneLcFDOs7NVOfPgA0vw7Q7Ufl8qysKK7FF6fSz5c9e+Ml9irI1SMVjAmZy8t2hydTP6tQb+Dpd3O1BlJMZVMeOYplU73m8TZlsRJ0C5SRBiknY7p3Bn4Qi0ufwyklK5fiGKqQOhOElNKicdvxTzE41KIGvgpNlbfetmH86K7/Qqu13UdHmMhHCdpLZl1lQQ1B/arca04vfFyluo3eRitnQBLDHUyjNVVi7YVhD8kn1WPUuaEIsnXpVq2Z4qhxDv7sUQAu6K1DqnjnWo6JOI+cgG2XBqjsQK3C+rMwBy78R7aAsWPNngwSYqC4pxZYehhe8v0k+vG/yVGKhvk1cWveaXwqi5p0PgJkMUnqD/P9Iy+3HN7fxamjZrUf7Gme4e5bMj2mEMGh1tnlHrO7NZzh3qGT+7dk3avaUICX/GrmNHcsULKqSO/NrOyL8XAxHVXp5cus9/xgOLFoLsY65g5Ev8xVoKZekSRZY16nx6IDmLDmTPGOaIzq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

