apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgCJZn8vUNwi3lvhrMVcf9MGdqSX91RlL1uWgV1tP4l1vVw27p+KveZ52idRTLDixENRzE71e+aW6tHSj1XZNpgvqmahPcq2ifWwcmeEcntxTtKSgG92Sj+Gnx1/pdSoJkaXBncoSY7cM52twNNGIFVakDpVzTtgz8soGqJX9Uj+hqTaF/NqR9E/yggozH3qtflDux01VKAoskwGXLVnzjYbI4IMbOLOighBb/8Yg18A1K8Z/6mVi/4MZYoSzSyCYmcKjtSs1gwsx1MbTcFyxZwasY9akJh509Lj/kHtSAuAjcPu4KDtmKifmJ2XhxAi/lO3mKIkL+ACKEEaw7UcKwLTMEXNdspoMgMMB7SbBT9tU3mzrK7hlG62VN1r3oAjUP1Tkqu+Kpx10e4eYOqbjJ++xH5BS7MAJtoaVYSyxQtUgZ7wBYUcKjZbCSnmJ3vv+GFwnHS3YU1TUpVaaXcc6pIeOiDh7glJhdqCZ2jtcs85L+UnPbPhJvhHg1iVKwrq7W2PFIY8VWxtlsrUexANfJ/wboETCp/dRuN6p094BSIapKXspw6Or/elSY4QZ/0QhO5AXyrKtcgixsjC+lUeV+buQkP5M4DmSr2InZ5VsKDuY1k3nSH3KgSMLrpRGpe907tworuS54PPPNU65w53yrjbR+6OLDFD6M2bWDS07kUkLDm1aacos6wQHpKBjgWGrhj0HBgsTr+Pa8ozAjUpV/MToc/clPTi3oxOGGBasD9bwjmKx971UFTqCugTYRJPFoIailrg6FPGQkiu98cxRdQtJ8bEa2nSszckgMP1tCiFbwtjsb9DRtbq+Sp+KzMvMgyEk/RiOX39ZVyRI0OrzTBwor1oyMtz/CuqR6qZhh7/GE5vZzRWDooIZwTM//t2JD1s41GkxMFQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

