apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgCTr38bWBwaKp/Yrw4SyijE5Ff3JarSCtqr+ulewQ/FAMePXkiUaAP5kygoRRL7jAwNLvElFjERsFWcpW93jY/xyNVW+tJRAxJDgzdhKQczCFOdGC8Esr6LBWdjY0tQ0dpkxRimvTjjTEP6q25FIh8TJjTdbcGawDsmnp8aMboF74yZ43YWGNzPjo5MvxLl7Y7+dR7hvVMHybfFBApV2BzzcEgnpkoRf/9Q28m9CODISWjy4Gj4WGB6KT28lHzDV7LcZt9NlmyorFliY9rNynnI53323P/uoa8wxypuLoNw6M/Wt8lic3XS546mIcTga4EsK5zLGSiWrrjxClGtV2lKc+xI+Nv64VcwMwvS0RFc9dNOKLKhFc6eVdHJ1AlWAVpLIsa1cn+h321Cg+R2je+Iw4a8YmbpMaszCnlmJ9Q+FIFaNWxsnUYg3+mJnA4G1CuOD6DglqdbYj2BsyF1GWadiHdI/SE53wUIPzL6HYRkew4jT0Gj/YG6+ucmtkGB07/+IYHSbD0h12TCfU4/49mtttzEH3M80Aa2dPlIlU+E+f1kxXuGfcbyAQ9PqobBs57CU0ZMT8yf7qQS2YnhMfXozU5vc4KgFEf0Cq+W73YLXQdlO7iOQPV1Gy7FZ/bIrqp6/3GIPsts1x0qobiJMiILHOGqcIlO5U7JnbJFZtxttMNNZ9QigBj6cKP8dmJHYcGkbRjtLm5PZC293SQqm6cFp6RSkEjzAI2ZJxL3yVQx4bb1eI09WXfioZeSMVFZzLORgC39U/LVahXA7EQd1HIC5EfN+bhn83ZI9YZaBhJXdiBLh9SkhBnY1yz+3/274+XBvdcVJE2yERQn0YKO0GHVLEW8sOfgECa07jpSIRg4UlBW2J6p/BBO2kxBFcRpxyWBolHgolNI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

