apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgAhAbL68z5+QoOHWbNAanzAft5qO63EO2x676FP7661BW4KOydVMcdzOynlpLfDA29QhgEBm1esSBbEsK9uJ8AVSFrjM5vRktHWkQCgTtA/i9vQSBvWDpZpHbkAxPoRTvr/OAvNwusEIcCiUOp0zoqpn39WbDccLPX304S3p5Dgkrkp4qSN3PKDLgeKM6sp+gJbT+vwPN5A77xymJdLe4kSw8qfj9UqxYDxl44HkE27wC0Yu1aFNsKpmvJYwB/evpcYePFV9s28lQGcBL6PTgZy35dFr4u7Q/ukTS2dTiTj5YNu6WVIpIcjXtCwdIuLnKCs843uKuBbp8y5l31xEmMzaxeJapVEpFhrsqkH7w9OEzZq3J5Jge9syENBHpD/lPZJS9wJK1j1enY3yRDKw5UwDolRGoRrnKVn/KXhD5azkpJLKKVKRfsoEdabOiGkGwqrRslJCAppRRS5RMs4ssl9rB3l5r94O24uQ85p90feKW9jtSjmt6yXBdkapG1KEXssGCUfLUFxE7/cDHCpZkyQXFQ1aeoZn2dTdlME8+GXFRlAcar80MAoEpHsilSFfprRebaR15RghxvgkyklrlMYb1Yrpn/ZOYwcqF0hRh1g9ZCLOepxMEFTiwvUqCOE6dPLZPOmzBuHzhKX/hJBCOGOdmtTXoMnn9UiWG/JGrwqJecYHshgyM30wqLZyM1oNukKjSUprf5cX227O+xEtW2L/pu507TnKwM6BRW3vW7rUPzKm4leJXeFN1BiW906oqHwQWUTK7GQTa3R1MBpbwOXHkLN8Ji5ZiPpFklZxqkWeVwz5aFHP8A/RliYNtVUTc9KwwlhGjiVFXIRo/2BYrkzIY8QEMft1ndKhSSknczcR+o9Ur908zXnjADoP1F+kImL9vK779ov
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: thanos-objstore
      namespace: monitoring

