apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mullvad
  namespace: media
spec:
  encryptedData:
    vpnConfigfile: AgB4aPwoh8gp2g6pNHxV58mlTq6OzuhtnSGVPbkC66YMZuK909PcIdewl8kes8TYwgmLaGfmjqALie36hO48m8eRKq4RtydNn8bO6OTYoElxaDLvxKzloIxs7ARn5Wosf6TmABu5pB3Gilm+jesnRpNoAvnKhfhtXM9wJ7u91sA+B0s/P0wFsGdQGjEZQfWWGDrx0UvxwXBzByoHB0CBe53L1PxuNDbvLz49Mi/DZpABIa51RfUvlmod9BaQBMcwtIBMslaxt8+VZW1YGd7ivl8olr05u9i+Sj9gaXicFN+EuTgw2+pMiAgpBQz26PNHzYrc1j/PPb+y+fEC6rh/DOpoqSfC+I4uMfe7jWjgZpuwCTIVXhq+eGK5JzGIJOdXcfQ8u1Ny2lgbFR8D8sJCn7wIAM31N3Ri6+XBE2GGR4wwhIRxZWxj5Ez0atNNOFKWRnld9Dbt68GWmK8ofyrUokJHMEoHonTA9X8ypFBoq866ho0w39qJvwlX8z7DklTVNncQm4NE/axHIGSSuMcXLRmHYGwp9sjk8zYe2W9ZmJal/lSRzJxggzqWQX8k9MzE9M2FBv5ERGE6/iD1eHVCpbsOz5/hZ+krUdmIcx0to2L5h5OsruwRgTHCiWUo+Z1FkwUeNOh/HbcWmDHVgTg2QWNdB7pvr4pTkqxF3+dKIMMfqbjS7dmuTFQGcHIXk6uVKKNYB/rE3eaOYfJnXjQD0vbBmyvSbNB3kXeESZLcYade6Pq/KYsZ7ymcP4ZmfzXbABYGTmX071ycpUxe3aUCKQO6nR38GNDomU9mtOwzWWChHIg1On6iSJqWmS/Iz9VC3eyoiJ/RAL7bptZllVPCEIsS6EWqG5KIq8mj2xPf7Nc9SXZXnt2MHbiyW63bSjRcFsuDuMk6ISpcFbkvy8KIJqIXOu9VPEnDx3/7iv4+Tffs+GNjtKlUc7PP39/jMFngZ8LcTRw/B5dB4anMpOMZ44dNZuaxKpRxSldW0BQ2PBNGNXPl/mLLImMplWTsPOc8ciqes4/VeCn9+G1rN2nC31qGBcmYWgaEB+QHoiNSJ8l2Qo52OvFcWoKf64AP8QngHcLcFlih88+9tncbZoFaRbiPzeOMgjVWudLCH6G2HmTbfP+yP5fxXGlaudMepL2FfPHQ8jHrZLgte8m2CDv6NplzXGUXD9nb/RcPVVrs8E9JfxnEdbQp//XpuFqSa1s+RV+fhXbakex0vOHQdNR6DgucgHZrYQ1l6w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mullvad
      namespace: media

