apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ombi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    path: charts/stable/ombi
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        controller:
          labels:
            pvc: "true"
        image:
          tag: latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: ombi
        ingress:
          main:
            enabled: true
            hosts:
            - host: request.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
        additionalContainers:
          - name: duplicacy
            image: alexphillips/duplicacy
            env:
              - name: TZ
                value: America/New_York
              - name: SCHEDULE
                value: "15 0 * * *"
              - name: BACKUP_NAME
                value: gcd-ombi
              - name: BACKUP_LOCATION
                value: gcd://duplicacy_backup/ombi
              - name: HC_API_URL
                value: https://hc.w00t.cloud/ping
              - name: CHECK_UUID
                value: d21bcefb-4b49-47be-95de-7c8fe53221bb
              - name: DUPLICACY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: password
              - name: GCD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: gcd_token
            volumeMounts:
              - mountPath: /data
                name: config
