haste-server:
  image:
    tag: latest
  env:
    TZ: America/New_York
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 128Mi
      retain: true
  ingress:
    main:
      enabled: true
      hosts:
      - host: haste.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
