tautulli:
  controller:
    labels:
      pvc: "true"
  persistence:
    config:
      enabled: true
      retain: true
      size: 5Gi
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: ttl.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    duplicacy:
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "45 0 * * *"
        - name: BACKUP_NAME
          value: gcd-tautulli
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/tautulli
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 91105625-60df-42da-a496-a6ed877e39dc
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
