healthchecks:
  image:
    repository: ghcr.io/linuxserver/healthchecks
    tag: latest
  env:
    PGID: 1000
    PUID: 1000
    TZ: America/New_York
    SITE_NAME: w00t.cloud
    SITE_ROOT: https://hc.w00t.cloud
  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: hc.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  initContainers:
    duplicacy-init:
      image: alexphillips/duplicacy-init
      env:
        - name: BACKUP_NAME
          value: gcd-healthchecks
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/healthchecks
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
  additionalContainers:
    duplicacy-backup:
      image: alexphillips/duplicacy-backup
      env:
        - name: SCHEDULE
          value: "30 01 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 233b56e0-a601-41ab-b8c7-54d6694ba973
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
