overseerr:
  controller:
    labels:
      pvc: "true"
  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: request.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    duplicacy:
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "45 9 * * *"
        - name: BACKUP_NAME
          value: gcd-overseerr
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/overseerr
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: b419dd11-68f1-444b-bdea-6c6496f6e897
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
