---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: funkwhale-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
