---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
