---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: loki.rules
  namespace: monitoring
spec:
  groups:
    - name: loki.rules
      rules:
        - alert: Test
          annotations:
            message: "This is a test alert"
          expr: |
            sum(rate({job="apps/uptime-kuma"} |= "Request failed"[10s])) > 0
          for: 1s
          labels:
            severity: critical
        - alert: RadarrReadOnly
          annotations:
            message: "Radarr's volume appears to be read-only"
          expr: |
            sum(rate({app="radarr"} |= "ReadOnly"[10s])) > 0
          for: 10s
          labels:
            severity: critical
