apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mealie
  project: default
  source:
    path: charts/stable/mealie
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        persistence:
          config:
            existingClaim: mealie
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
