---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: apps
  labels:
    argocd.argoproj.io/instance: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
