apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: utilities
  project: default
  source:
    path: charts/stable/bookstack
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            type: custom
            volumeSpec:
              nfs:
                server: 192.168.1.91
                path: /mnt/storage/docker/bookstack
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: wiki.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
