apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/bookstack
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        controller:
          labels:
            pvc: "true"
        image:
          tag: latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/New_York
          APP_URL: https://wiki.w00t.cloud
        persistence:
          config:
            enabled: true
            existingClaim: bookstack
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: wiki.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
        additionalContainers:
          - name: duplicacy
            image: alexphillips/duplicacy
            env:
              - name: TZ
                value: America/New_York
              - name: SCHEDULE
                value: "15 3 * * *"
              - name: BACKUP_NAME
                value: gcd-bookstack
              - name: BACKUP_LOCATION
                value: gcd://duplicacy_backup/bookstack
              - name: HC_API_URL
                value: https://hc.w00t.cloud/ping
              - name: CHECK_UUID
                value: d986e8fc-cf32-4e27-a674-90fb549c6ef6
              - name: DUPLICACY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: password
              - name: GCD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: gcd_token
            volumeMounts:
              - mountPath: /data
                name: config
