apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/bookstack
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/New_York
          APP_URL: https://wiki.w00t.cloud
        persistence:
          config:
            enabled: true
            existingClaim: bookstack
        ingress:
          main:
            enabled: true
            annotations:
            hosts:
            - host: wiki.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
