apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: utilities
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
