---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xbackbone
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
