argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.0.5
  dex:
    enabled: false
  server:
    extraArgs:
      - "--insecure"
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

argocd-applicationset:
  image:
    repository: quay.io/argocdapplicationset/argocd-applicationset
    tag: v0.1.0

  args:
    policy: create-update
