apprise-api:
  image:
    repository: ghcr.io/linuxserver-labs/apprise-api
    tag: latest

  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      hosts:
      - host: apprise.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
