apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: apps
data:
  config: |
    # Input plugins

    # Ping plugin
    [[inputs.ping]]
    urls = ["1.1.1.1", "192.168.1.1", "192.168.100.1", "google.com", "reddit.com"]
    count = 4
    ping_interval = 1.0
    timeout = 2.0

    # DNS plugin
    [[inputs.dns_query]]
      servers = ["8.8.8.8", "1.1.1.1"]
      domains = ["google.com", "reddit.com"]

    # Output format plugins
    [[outputs.prometheus_client]]
      listen = ":9283"
      metric_version = 2
