snipe-it:
  env:
    APP_URL: https://it.w00t.cloud
    MYSQL_PORT_3306_TCP_ADDR: 192.168.1.91
    MYSQL_PORT_3306_TCP_PORT: 3306
    MYSQL_DATABASE: snipeit
    MYSQL_USER: snipeit
    MYSQL_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: snipe-it
          key: mysql_password

  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: it.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/snipe-it
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "15 3 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 0ee715f6-f491-41a6-a2f6-a57421e34dde
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/snipe-it
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config
