snipe-it:
  env:
    APP_URL: https://it.w00t.cloud
    MYSQL_PORT_3306_TCP_ADDR: 192.168.1.91
    MYSQL_PORT_3306_TCP_PORT: 3306
    MYSQL_DATABASE: snipeit
    MYSQL_USER: snipeit
    MYSQL_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: snipe-it
          key: mysql_password

  persistence:
    config:
      enabled: true
      retain: true
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: it.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    duplicacy-init:
      image: alexphillips/duplicacy-init
      env:
        - name: BACKUP_NAME
          value: gcd-snipeit
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/snipeit
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    duplicacy-backup:
      image: alexphillips/duplicacy-backup
      env:
        - name: SCHEDULE
          value: "15 3 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud
        - name: CHECK_UUID
          value: 0ee715f6-f491-41a6-a2f6-a57421e34dde
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: config
