---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
