drone:
  ingress:
    enabled: true
    hosts:
      - host: ci.w00t.cloud
        paths:
          - "/"
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: longhorn
  extraSecretNamesForEnvFrom:
    - drone
drone-runner-kube:
  extraSecretNamesForEnvFrom:
    - drone
