drone:
  image:
    repository: drone/drone
    tag: 2.4.0

  env:
    - name: DRONE_GITEA_SERVER
      value: https://git.w00t.cloud
    - name: DRONE_GIT_ALWAYS_AUTH
      value: true
    - name: DRONE_GITEA_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: gitea
          key: client_id
    - name: DRONE_GITEA_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gitea
          key: client_secret
    - name: DRONE_SERVER_HOST
      value: ci.w00t.cloud
    - name: DRONE_SERVER_PROTO
      value: https
    - name: DRONE_RPC_SECRET
      valueFrom:
        secretKeyRef:
          name: drone
          key: rpc_secret
    - name: DRONE_USER_CREATE
      value: username:alex,admin:true

  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        ingress.kubernetes.io/protocol: https
      hosts:
      - host: ci.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  additionalContainers:
    drone-runner:
      image: drone/drone-runner-docker:latest
      env:
        - name: DRONE_RPC_PROTO
          value: https
        - name: DRONE_RPC_HOST
          value: ci.w00t.cloud
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone
              key: rpc_secret
        - name: DRONE_RUNNER_CAPACITY
          value: 2
        - name: DRONE_RUNNER_NAME
          value: runner
