---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ng
  namespace: apps
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
