uptime-kuma:
  persistence:
    data:
      enabled: true
      retain: true
      size: 512Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn
  ingress:
    main:
      enabled: true
      hosts:
      - host: status.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
  additionalContainers:
    - name: duplicacy
      image: alexphillips/duplicacy
      env:
        - name: TZ
          value: America/New_York
        - name: SCHEDULE
          value: "00 15 * * *"
        - name: BACKUP_NAME
          value: gcd-uptime-kuma
        - name: BACKUP_LOCATION
          value: gcd://duplicacy_backup/uptime-kuma
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 705dbe72-8898-4737-b3a4-aabd52099de1
        - name: DUPLICACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: password
        - name: GCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: duplicacy
              key: gcd_token
      volumeMounts:
        - mountPath: /data
          name: data
