uptime-kuma:
  global:
    fullnameOverride: uptime-kuma-web
  image:
    repository: louislam/uptime-kuma
    tag: 1.11.1

  persistence:
    data:
      enabled: true
      retain: true
      size: 512Mi
      accessMode: ReadWriteOnce
      storageClass: longhorn

  ingress:
    main:
      enabled: true
      hosts:
      - host: status.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  dnsPolicy: None

  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/uptime-kuma
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: data

  additionalContainers:
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "00 15 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: 705dbe72-8898-4737-b3a4-aabd52099de1
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/uptime-kuma
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: data
