uptime-kuma:
  persistence:
    data:
      enabled: true
      existingClaim: uptime-kuma
  ingress:
    main:
      enabled: true
      hosts:
      - host: status.w00t.cloud
        paths:
        - path: /
          pathType: Prefix
