apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/home-assistant
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        controller:
          labels:
            pvc: "true"
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: home-assistant
        ingress:
          main:
            enabled: true
            hosts:
            - host: ha.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
        addons:
          codeserver:
            enabled: true
            volumeMounts:
              - mountPath: /data
                name: config
        additionalContainers:
          - name: duplicacy
            image: alexphillips/duplicacy
            env:
              - name: TZ
                value: America/New_York
              - name: SCHEDULE
                value: "30 0 * * *"
              - name: BACKUP_NAME
                value: gcd-homeassistant
              - name: BACKUP_LOCATION
                value: gcd://duplicacy_backup/homeassistant
              - name: HC_API_URL
                value: https://hc.w00t.cloud/ping
              - name: CHECK_UUID
                value: 7213e9b6-c993-4a58-a747-57022c45ce92
              - name: DUPLICACY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: password
              - name: GCD_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: duplicacy
                    key: gcd_token
            volumeMounts:
              - mountPath: /data
                name: config
