apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: default
  source:
    path: charts/stable/home-assistant
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: home-assistant
          node-red:
            enabled: true
            existingClaim: node-red
            mountPath: '-'
        ingress:
          main:
            enabled: true
            hosts:
            - host: ha.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
          node-red:
            enabled: true
            primary: false
            hosts:
            - host: node.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
                service:
                  name: home-assistant-node-red
                  port: 1880
        service:
          node-red:
            enabled: true
            ports:
              node-red-http:
                enabled: true
                port: 1880
                protocol: HTTP
        additionalContainers:
          - name: node-red
            image: nodered/node-red
            env:
              - name: TZ
                value: America/New_York
            ports:
              - containerPort: 1880
            volumeMounts:
              - mountPath: /data
                name: node-red
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
