apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    path: charts/stable/home-assistant
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          config:
            enabled: true
            existingClaim: home-assistant
        ingress:
          main:
            enabled: true
            hosts:
            - host: ha.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
