apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lychee-other
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  project: default
  source:
    path: charts/stable/lychee
    repoURL: https://github.com/k8s-at-home/charts
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        env:
          TZ: America/New_York
        persistence:
          media:
            enabled: true
            type: custom
            readOnly: true
            volumeSpec:
              nfs:
                server: 192.168.1.91
                path: /mnt/storage/organize/piwigo-albums
          config:
            enabled: true
            existingClaim: lychee-other-config
          uploads:
            enabled: true
            existingClaim: lychee-other-uploads
          sym:
            enabled: true
            existingClaim: lychee-other-sym
        ingress:
          main:
            enabled: true
            hosts:
            - host: other.w00t.cloud
              paths:
              - path: /
                pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
