radarr:
  image:
    repository: ghcr.io/k8s-at-home/radarr
    tag: v3.2.2.5080

  controller:
    labels:
      nfs: "true"

  env:
    TZ: America/New_York

  persistence:
    config:
      enabled: true
      retain: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: longhorn
    media:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: 192.168.1.91
          path: /mnt/storage
      mountPath: /mnt/storage

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

  ingress:
    main:
      enabled: true
      annotations:
      hosts:
      - host: rdr.w00t.cloud
        paths:
        - path: /
          pathType: Prefix

  initContainers:
    restic-init:
      image: alexphillips/restic
      command: ["/scripts/restic-init.sh"]
      env:
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/radarr
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config

  additionalContainers:
    restic-backup:
      image: alexphillips/restic
      env:
        - name: SCHEDULE
          value: "45 0 * * *"
        - name: HC_API_URL
          value: https://hc.w00t.cloud/ping
        - name: CHECK_UUID
          value: f3888abb-4149-416a-a066-4b451e27eb25
        - name: RESTIC_REPOSITORY
          value: rclone:gdrive:restic/radarr
        - name: RESTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: RCLONE_CONF
          valueFrom:
            secretKeyRef:
              name: rclone
              key: config
      volumeMounts:
        - mountPath: /data
          name: config
